/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AmericanFlag2Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AmericanFlag2AddonDeed();
			}
		}

		[ Constructable ]
		public AmericanFlag2Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 169 );
			ac.Hue = 2998;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 169 );
			ac.Hue = 2998;
			AddComponent( ac, 0, -1, 20 );
			ac = new AddonComponent( 169 );
			ac.Hue = 2998;
			AddComponent( ac, 0, -1, 40 );
			ac = new AddonComponent( 2233 );
			ac.Hue = 2998;
			AddComponent( ac, 0, -1, 52 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 0, 47 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 1, 46 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 2, 47 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 0, 48 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 1, 47 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 2, 48 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 0, 49 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 1, 48 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 2, 49 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 0, 50 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 1, 49 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 2, 50 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 0, 51 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 1, 50 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 2, 51 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 0, 52 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 1, 51 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 2, 52 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 1, 52 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 2, 53 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 2;
			AddComponent( ac, 0, 0, 53 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 2;
			AddComponent( ac, 0, 0, 54 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 1, 53 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 2, 54 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 2;
			AddComponent( ac, 0, 0, 55 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 1, 54 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 2, 55 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 2;
			AddComponent( ac, 0, 0, 57 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 1, 55 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 2, 56 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 2;
			AddComponent( ac, 0, 0, 56 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 1, 56 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 2, 57 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 2;
			AddComponent( ac, 0, 0, 58 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 1, 57 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 1153;
			AddComponent( ac, 0, 2, 58 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 2;
			AddComponent( ac, 0, 0, 59 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 1, 58 );
			ac = new AddonComponent( 2252 );
			ac.Hue = 37;
			AddComponent( ac, 0, 2, 59 );
			ac = new AddonComponent( 8477 );
			AddComponent( ac, 0, -1, 58 );
			ac = new AddonComponent( 2251 );
			ac.Hue = 37;
			AddComponent( ac, 0, 1, 59 );
			ac = new AddonComponent( 2251 );
			ac.Hue = 37;
			AddComponent( ac, 0, 0, 46 );
			ac = new AddonComponent( 3207 );
			ac.Hue = 2;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 3262 );
			ac.Hue = 37;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3214 );
			ac.Hue = 1153;
			AddComponent( ac, 1, 0, 0 );

		}

		public AmericanFlag2Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AmericanFlag2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AmericanFlag2Addon();
			}
		}

		[Constructable]
		public AmericanFlag2AddonDeed()
		{
			Name = "AmericanFlag2";
		}

		public AmericanFlag2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}