/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AwardPlatformAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AwardPlatformAddonDeed();
			}
		}

		[ Constructable ]
		public AwardPlatformAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -5, -2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -5, -1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -5, 0, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -5, 1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -5, 2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -4, -3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -4, -2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -4, -1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -4, 0, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -4, 1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -4, 2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -4, 3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -3, -3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -3, -2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -3, -1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -3, 0, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -3, 1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -3, 2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -3, 3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -2, -3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -2, -2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -2, -1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -2, 0, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -2, 2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -2, 3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -1, -3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -1, 2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, -1, 3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 0, -3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 0, 3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 1, -3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 1, -2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 1, 3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 2, -3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 2, -2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 2, 3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 3, -3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 3, -2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 3, -1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 3, 0, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 3, 1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 3, 2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 3, 3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 4, -3, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 4, -2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 4, -1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 4, 0, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 4, 1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 4, 2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 4, 3, 1 );
			ac = new AddonComponent( 1983 );
			AddComponent( ac, -5, -3, 1 );
			ac = new AddonComponent( 1985 );
			AddComponent( ac, -5, 3, 1 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 54;
			AddComponent( ac, -1, -3, 3 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1263;
			AddComponent( ac, 0, -3, 3 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1263;
			AddComponent( ac, 0, -3, 8 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 32;
			AddComponent( ac, 1, -3, 3 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 32;
			AddComponent( ac, 1, -3, 8 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1263;
			AddComponent( ac, 0, -3, 13 );
			ac = new AddonComponent( 1 );
			AddComponent( ac, -4, -3, 3 );
			ac = new AddonComponent( 4825 );
			AddComponent( ac, -4, -3, 3 );
			ac = new AddonComponent( 1 );
			AddComponent( ac, 4, -3, 3 );
			ac = new AddonComponent( 4825 );
			AddComponent( ac, 4, -3, 3 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 5, -2, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 5, -1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 5, 0, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 5, 1, 1 );
			ac = new AddonComponent( 1981 );
			AddComponent( ac, 5, 2, 1 );
			ac = new AddonComponent( 1984 );
			AddComponent( ac, 5, -3, 0 );
			ac = new AddonComponent( 1990 );
			AddComponent( ac, 5, 3, 1 );

		}

		public AwardPlatformAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AwardPlatformAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AwardPlatformAddon();
			}
		}

		[Constructable]
		public AwardPlatformAddonDeed()
		{
			Name = "AwardPlatform";
		}

		public AwardPlatformAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}