/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BazzarTentSmall2FSAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BazzarTentSmall2FSAddonDeed();
			}
		}

		[ Constructable ]
		public BazzarTentSmall2FSAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 876 );
			ac.Hue = 1368;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1631 );
			ac.Hue = 1368;
			AddComponent( ac, 1, -1, 25 );
			ac = new AddonComponent( 1632 );
			ac.Hue = 1368;
			AddComponent( ac, 0, 2, 25 );
			ac = new AddonComponent( 1631 );
			ac.Hue = 1368;
			AddComponent( ac, 0, -1, 25 );
			ac = new AddonComponent( 1633 );
			ac.Hue = 1368;
			AddComponent( ac, 2, 1, 25 );
			ac = new AddonComponent( 1633 );
			ac.Hue = 1368;
			AddComponent( ac, 2, 0, 25 );
			ac = new AddonComponent( 1630 );
			ac.Hue = 1368;
			AddComponent( ac, -1, 0, 25 );
			ac = new AddonComponent( 1632 );
			ac.Hue = 1368;
			AddComponent( ac, 1, 2, 25 );
			ac = new AddonComponent( 2771 );
			ac.Hue = 8;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 57;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2772 );
			ac.Hue = 8;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1637 );
			ac.Hue = 1368;
			AddComponent( ac, -1, -1, 25 );
			ac = new AddonComponent( 2777 );
			ac.Hue = 10;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1638 );
			ac.Hue = 1368;
			AddComponent( ac, -1, 2, 25 );
			ac = new AddonComponent( 1630 );
			ac.Hue = 1368;
			AddComponent( ac, -1, 1, 25 );
			ac = new AddonComponent( 1636 );
			ac.Hue = 1368;
			AddComponent( ac, 2, -1, 25 );
			ac = new AddonComponent( 2774 );
			ac.Hue = 10;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 877 );
			ac.Hue = 57;
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 879 );
			ac.Hue = 1368;
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 874 );
			ac.Hue = 57;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 874 );
			ac.Hue = 1368;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 881 );
			ac.Hue = 1368;
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 881 );
			ac.Hue = 57;
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1636 );
			ac.Hue = 57;
			AddComponent( ac, 1, 0, 28 );
			ac = new AddonComponent( 1635 );
			ac.Hue = 57;
			AddComponent( ac, 1, 1, 28 );
			ac = new AddonComponent( 1637 );
			ac.Hue = 57;
			AddComponent( ac, 0, 0, 28 );
			ac = new AddonComponent( 1635 );
			ac.Hue = 1368;
			AddComponent( ac, 2, 2, 25 );
			ac = new AddonComponent( 875 );
			ac.Hue = 1359;
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 879 );
			ac.Hue = 57;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 872 );
			ac.Hue = 1368;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1638 );
			ac.Hue = 57;
			AddComponent( ac, 0, 1, 28 );

		}

		public BazzarTentSmall2FSAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BazzarTentSmall2FSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BazzarTentSmall2FSAddon();
			}
		}

		[Constructable]
		public BazzarTentSmall2FSAddonDeed()
		{
			Name = "BazzarTentSmall2FS";
		}

		public BazzarTentSmall2FSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}