/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BFlowerPotFoxAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BFlowerPotFoxAddonDeed();
			}
		}

		[ Constructable ]
		public BFlowerPotFoxAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 3633 );
			ac.Light = LightType.Circle225;
			ac.Hue = 1056;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2541 );
			ac.Hue = 1056;
			AddComponent( ac, 0, 0, 3 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 0, 0, 8 );

		}

		public BFlowerPotFoxAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BFlowerPotFoxAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BFlowerPotFoxAddon();
			}
		}

		[Constructable]
		public BFlowerPotFoxAddonDeed()
		{
			Name = "BFlowerPotFox";
		}

		public BFlowerPotFoxAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}