
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class blackwindsstatueAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3236, 0, 2, 0}, {3236, 2, 0, 3}// 8	9	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new blackwindsstatueAddonDeed();
			}
		}

		[ Constructable ]
		public blackwindsstatueAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 9325, 0, 0, 0, 2590, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 9325, 1, 0, 0, 2590, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 9325, 0, 1, 0, 2590, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3368, 1, 2, 3, 2590, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3368, 2, 1, 0, 2747, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3370, 0, 2, 0, 2747, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3374, 2, 2, 3, 2747, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 11539, 1, 1, 0, 2747, -1, "Blackwind", 1);// 10
			AddComplexComponent( (BaseAddon) this, 3366, 1, -1, 1, 2749, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3366, -1, 1, 0, 2749, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 3372, 2, 0, 3, 2747, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 3372, 2, 1, 6, 2826, -1, "", 1);// 14

		}

		public blackwindsstatueAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class blackwindsstatueAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new blackwindsstatueAddon();
			}
		}

		[Constructable]
		public blackwindsstatueAddonDeed()
		{
			Name = "blackwindsstatue";
		}

		public blackwindsstatueAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}