
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BloodyWellAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7385, 0, 0, 15}, {7385, 1, 0, 15}, {7385, 1, 1, 15}// 7	8	9	
			, {7382, 1, -1, 15}, {7382, 0, -1, 15}, {7378, -1, 0, 15}// 10	11	12	
			, {7378, -1, 1, 15}, {7375, -1, -1, 15}, {7405, 0, 0, 15}// 13	14	15	
			, {7393, 0, 1, 15}, {6924, 0, 0, 10}, {6927, 0, 1, 9}// 17	18	19	
			, {7385, 0, 1, 15}// 20	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BloodyWellAddonDeed();
			}
		}

		[ Constructable ]
		public BloodyWellAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 9535, -1, 0, 0, 2856, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 9537, 0, -1, 0, 2856, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 9539, 2, 1, 0, 2856, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 9546, -1, 1, 0, 2856, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 9551, 1, -1, 0, 2856, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 9553, 2, 0, 0, 2856, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 7408, 1, 0, 15, 2450, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 9544, 1, 2, 0, 2856, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 9548, 0, 2, 0, 2856, -1, "", 1);// 22

		}

		public BloodyWellAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BloodyWellAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BloodyWellAddon();
			}
		}

		[Constructable]
		public BloodyWellAddonDeed()
		{
			Name = "BloodyWell";
		}

		public BloodyWellAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}