
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BlueXHallRunnerNSAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2810, 0, -3, 0}, {2810, 0, -2, 0}, {2810, 0, -1, 0}// 1	2	3	
			, {2810, 0, 0, 0}, {2810, 0, 1, 0}, {2810, 0, 2, 0}// 4	5	6	
			, {2810, 0, 3, 0}, {2810, 0, 4, 0}, {2808, 1, -3, 0}// 7	8	9	
			, {2808, 1, -2, 0}, {2808, 1, -1, 0}, {2808, 1, 0, 0}// 10	11	12	
			, {2808, 1, 1, 0}, {2808, 1, 2, 0}, {2808, 1, 3, 0}// 13	14	15	
			, {2808, 1, 4, 0}, {2806, -1, -3, 0}, {2806, -1, -2, 0}// 16	17	18	
			, {2806, -1, -1, 0}, {2806, -1, 0, 0}, {2806, -1, 1, 0}// 19	20	21	
			, {2806, -1, 2, 0}, {2806, -1, 3, 0}, {2806, -1, 4, 0}// 22	23	24	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BlueXHallRunnerNSAddonDeed();
			}
		}

		[ Constructable ]
		public BlueXHallRunnerNSAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public BlueXHallRunnerNSAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BlueXHallRunnerNSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BlueXHallRunnerNSAddon();
			}
		}

		[Constructable]
		public BlueXHallRunnerNSAddonDeed()
		{
			Name = "BlueXHallRunnerNS";
		}

		public BlueXHallRunnerNSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}