
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CompassionShrineAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {5291, 0, 0, 0}, {5292, 0, 1, 0}, {5293, 1, 1, 0}// 1	2	3	
			, {5294, 1, 0, 0}, {4, 0, -1, 0}, {5, 1, -1, 0}// 4	5	6	
			, {9037, -1, 0, 0}, {9036, 2, 0, 0}, {7108, 1, 2, 4}// 8	9	10	
			, {5128, 0, 2, 0}, {3149, 0, 2, 0}, {3149, 1, 2, 0}// 11	12	13	
			, {3149, 2, 1, 0}, {3149, 0, 1, 0}, {3149, 2, 2, 0}// 14	15	16	
			, {6811, -1, 2, 0}, {6811, 2, 2, 0}, {8454, -1, 1, 0}// 17	18	19	
			, {8455, 2, 1, 0}// 20	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CompassionShrineAddonDeed();
			}
		}

		[ Constructable ]
		public CompassionShrineAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 7188, 1, -1, 4, 0, 1, "", 1);// 7

		}

		public CompassionShrineAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CompassionShrineAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CompassionShrineAddon();
			}
		}

		[Constructable]
		public CompassionShrineAddonDeed()
		{
			Name = "CompassionShrine";
		}

		public CompassionShrineAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}