/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CraftShopSandstoneOneFloorAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CraftShopSandstoneOneFloorAddonDeed();
			}
		}

		[ Constructable ]
		public CraftShopSandstoneOneFloorAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 9478 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 9478 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 8662 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 970 );
			AddComponent( ac, -3, -4, 0 );
			ac = new AddonComponent( 969 );
			AddComponent( ac, -3, -3, 0 );
			ac = new AddonComponent( 3210 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 8662 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 8662 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 969 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 6795 );
			AddComponent( ac, -3, 5, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 2, 3, 26 );
			ac = new AddonComponent( 6020 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 6022 );
			AddComponent( ac, -2, 5, 0 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 967 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 4, 0, 20 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, 0, 1, 26 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, -3, 29 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 4, -2, 20 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -2, 4, 20 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 3, -2, 23 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -2, -2, 20 );
			ac = new AddonComponent( 9473 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, 0, 2, 26 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, 0, 3, 26 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, 2, 29 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, 0, 0, 26 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, 0, -1, 26 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, 0, -2, 26 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -1, -3, 23 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -1, 4, 23 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -1, -2, 23 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, 1, 5, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -2, 3, 20 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, 0, 29 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 2, 5, 0 );
			ac = new AddonComponent( 9479 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, -1, 5, 0 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -1, 3, 23 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -1, 0, 23 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 2, -3, 26 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 3, 4, 23 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, 1, 29 );
			ac = new AddonComponent( 968 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 6020 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 6021 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, -2, 29 );
			ac = new AddonComponent( 9476 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -2, -3, 20 );
			ac = new AddonComponent( 9479 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 968 );
			AddComponent( ac, 2, -4, 0 );
			ac = new AddonComponent( 968 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -1, 2, 23 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 3, -1, 23 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, 4, 29 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 2, 2, 26 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 6021 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 3, -3, 23 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 3, 5, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 4, 1, 20 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, 3, 29 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 4, -1, 20 );
			ac = new AddonComponent( 6020 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 3223 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 8662 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -2, 2, 20 );
			ac = new AddonComponent( 968 );
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -2, -1, 20 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 4, 4, 20 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 4, -3, 20 );
			ac = new AddonComponent( 6021 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 3, 3, 23 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 2, 4, 26 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 2, 0, 26 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 3, 0, 23 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 2, -1, 26 );
			ac = new AddonComponent( 6021 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 4, 2, 20 );
			ac = new AddonComponent( 968 );
			AddComponent( ac, 3, -4, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -2, 1, 20 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 968 );
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 24 );
			AddComponent( ac, -1, 3, 20 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 8662 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 3258 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6025 );
			AddComponent( ac, 3, 5, 0 );
			ac = new AddonComponent( 6021 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 6021 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 2, 1, 26 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, 0, 4, 26 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 3, 2, 23 );
			ac = new AddonComponent( 968 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 969 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 6020 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 6019 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 3, 1, 23 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, 0, -3, 26 );
			ac = new AddonComponent( 6021 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 8662 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 2, -2, 26 );
			ac = new AddonComponent( 1474 );
			AddComponent( ac, 1, -1, 29 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -1, 1, 23 );
			ac = new AddonComponent( 970 );
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 1181 );
			AddComponent( ac, -2, 5, 0 );
			ac = new AddonComponent( 24 );
			AddComponent( ac, 0, 3, 20 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -1, -1, 23 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6021 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 8564 );
			AddComponent( ac, -2, 0, 20 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 1183 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1184 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 8561 );
			AddComponent( ac, 4, 3, 20 );
			ac = new AddonComponent( 2879 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2879 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 2877 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2877 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 7153 );
			AddComponent( ac, 2, 2, 9 );
			ac = new AddonComponent( 6791 );
			AddComponent( ac, -1, 5, 0 );
			ac = new AddonComponent( 6792 );
			AddComponent( ac, -2, 5, 0 );
			ac = new AddonComponent( 4985 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 4984 );
			AddComponent( ac, 4, 5, 0 );

		}

		public CraftShopSandstoneOneFloorAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CraftShopSandstoneOneFloorAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CraftShopSandstoneOneFloorAddon();
			}
		}

		[Constructable]
		public CraftShopSandstoneOneFloorAddonDeed()
		{
			Name = "CraftShopSandstoneOneFloor";
		}

		public CraftShopSandstoneOneFloorAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}