/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CraftShopMedievalOneFloorWEAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CraftShopMedievalOneFloorWEAddonDeed();
			}
		}

		[ Constructable ]
		public CraftShopMedievalOneFloorWEAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -4, -3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -4, -4, 0 );
			ac = new AddonComponent( 204 );
			AddComponent( ac, -5, -4, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -5, -3, 0 );
			ac = new AddonComponent( 10079 );
			AddComponent( ac, -5, -2, 0 );
			ac = new AddonComponent( 10079 );
			AddComponent( ac, -5, -1, 0 );
			ac = new AddonComponent( 9158 );
			AddComponent( ac, -5, -2, 16 );
			ac = new AddonComponent( 9158 );
			AddComponent( ac, -5, -3, 16 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, -4, -4, 16 );
			ac = new AddonComponent( 9157 );
			AddComponent( ac, -4, -2, 19 );
			ac = new AddonComponent( 9168 );
			AddComponent( ac, -5, -4, 16 );
			ac = new AddonComponent( 9167 );
			AddComponent( ac, -4, -3, 19 );
			ac = new AddonComponent( 9158 );
			AddComponent( ac, -5, -1, 16 );
			ac = new AddonComponent( 9157 );
			AddComponent( ac, -4, -1, 19 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 10079 );
			AddComponent( ac, -5, 0, 0 );
			ac = new AddonComponent( 10079 );
			AddComponent( ac, -5, 1, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, -5, 2, 0 );
			ac = new AddonComponent( 211 );
			AddComponent( ac, -5, 3, 0 );
			ac = new AddonComponent( 211 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 3231 );
			AddComponent( ac, -5, 3, 0 );
			ac = new AddonComponent( 6022 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 1 );
			AddComponent( ac, -5, 4, 0 );
			ac = new AddonComponent( 3286 );
			AddComponent( ac, -5, 4, 0 );
			ac = new AddonComponent( 3287 );
			AddComponent( ac, -5, 4, 0 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, -4, 3, 16 );
			ac = new AddonComponent( 9158 );
			AddComponent( ac, -5, 2, 16 );
			ac = new AddonComponent( 9158 );
			AddComponent( ac, -5, 1, 16 );
			ac = new AddonComponent( 9158 );
			AddComponent( ac, -5, 0, 16 );
			ac = new AddonComponent( 9157 );
			AddComponent( ac, -4, 1, 19 );
			ac = new AddonComponent( 9157 );
			AddComponent( ac, -4, 0, 19 );
			ac = new AddonComponent( 9164 );
			AddComponent( ac, -5, 3, 16 );
			ac = new AddonComponent( 9163 );
			AddComponent( ac, -4, 2, 19 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -3, -3, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 5, -3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, -3, -4, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 2, -4, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 3, -4, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 4, -4, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 5, -4, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, 5, -3, 0 );
			ac = new AddonComponent( 10079 );
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 10079 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 210 );
			AddComponent( ac, 6, -3, 0 );
			ac = new AddonComponent( 210 );
			AddComponent( ac, 6, -4, 0 );
			ac = new AddonComponent( 2880 );
			AddComponent( ac, -3, -3, 0 );
			ac = new AddonComponent( 2878 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 2878 );
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 2880 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 2878 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 2878 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 2880 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 3232 );
			AddComponent( ac, 6, -3, 0 );
			ac = new AddonComponent( 3235 );
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 1 );
			AddComponent( ac, 0, -1, 16 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, -2, -4, 16 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, -1, -4, 16 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, 0, -4, 16 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, -2, -3, 19 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, -1, -3, 19 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 0, -3, 19 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, -2, -2, 22 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, -1, -2, 22 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 0, -2, 22 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, -1, -1, 25 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 0, -1, 25 );
			ac = new AddonComponent( 9167 );
			AddComponent( ac, -2, -1, 25 );
			ac = new AddonComponent( 9156 );
			AddComponent( ac, 6, -2, 16 );
			ac = new AddonComponent( 9156 );
			AddComponent( ac, 6, -3, 16 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, 1, -4, 16 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, 2, -4, 16 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, 3, -4, 16 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, 4, -4, 16 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, 4, -4, 16 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, 5, -4, 16 );
			ac = new AddonComponent( 9155 );
			AddComponent( ac, 5, -2, 19 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 1, -3, 19 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 2, -3, 19 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 3, -3, 19 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 4, -3, 19 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 1, -2, 22 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 2, -2, 22 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 3, -2, 22 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 2, -2, 25 );
			ac = new AddonComponent( 9166 );
			AddComponent( ac, 6, -4, 16 );
			ac = new AddonComponent( 9165 );
			AddComponent( ac, 5, -3, 19 );
			ac = new AddonComponent( 9165 );
			AddComponent( ac, 4, -2, 22 );
			ac = new AddonComponent( 9156 );
			AddComponent( ac, 6, -1, 16 );
			ac = new AddonComponent( 9155 );
			AddComponent( ac, 5, -1, 19 );
			ac = new AddonComponent( 9155 );
			AddComponent( ac, 4, -1, 22 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 1, -1, 25 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, 2, -1, 25 );
			ac = new AddonComponent( 9165 );
			AddComponent( ac, 3, -1, 25 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, -3, -4, 16 );
			ac = new AddonComponent( 9159 );
			AddComponent( ac, -3, -3, 19 );
			ac = new AddonComponent( 9167 );
			AddComponent( ac, -3, -2, 22 );
			ac = new AddonComponent( 9157 );
			AddComponent( ac, -3, -1, 22 );
			ac = new AddonComponent( 1 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 1304 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 5, 4, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 200 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 10079 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 10079 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 201 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 211 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 211 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 211 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 210 );
			AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 2917 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 2918 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 4218 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 6025 );
			AddComponent( ac, 5, 4, 0 );
			ac = new AddonComponent( 3246 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 3246 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 3246 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 3259 );
			AddComponent( ac, 6, 3, 0 );
			ac = new AddonComponent( 3231 );
			AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, -2, 3, 16 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, -1, 3, 16 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, 0, 3, 16 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, -2, 2, 19 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, -1, 2, 19 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 0, 2, 19 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, -2, 1, 22 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, -1, 1, 22 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 0, 1, 22 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, -1, 0, 25 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 0, 0, 25 );
			ac = new AddonComponent( 9163 );
			AddComponent( ac, -2, 0, 25 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, 1, 3, 16 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, 2, 3, 16 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, 3, 3, 16 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, 4, 3, 16 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, 5, 3, 16 );
			ac = new AddonComponent( 9156 );
			AddComponent( ac, 6, 2, 16 );
			ac = new AddonComponent( 9156 );
			AddComponent( ac, 6, 1, 16 );
			ac = new AddonComponent( 9156 );
			AddComponent( ac, 6, 0, 16 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 1, 2, 19 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 2, 2, 19 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 3, 2, 19 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 4, 2, 19 );
			ac = new AddonComponent( 9155 );
			AddComponent( ac, 5, 1, 19 );
			ac = new AddonComponent( 9155 );
			AddComponent( ac, 5, 0, 19 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 1, 1, 22 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 2, 1, 22 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 3, 1, 22 );
			ac = new AddonComponent( 9155 );
			AddComponent( ac, 4, 0, 22 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 1, 0, 25 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, 2, 0, 25 );
			ac = new AddonComponent( 9161 );
			AddComponent( ac, 5, 2, 19 );
			ac = new AddonComponent( 9161 );
			AddComponent( ac, 4, 1, 22 );
			ac = new AddonComponent( 9161 );
			AddComponent( ac, 3, 0, 25 );
			ac = new AddonComponent( 9162 );
			AddComponent( ac, 6, 3, 16 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, -3, 3, 16 );
			ac = new AddonComponent( 9153 );
			AddComponent( ac, -3, 2, 19 );
			ac = new AddonComponent( 9157 );
			AddComponent( ac, -3, 0, 22 );
			ac = new AddonComponent( 9163 );
			AddComponent( ac, -3, 1, 22 );

		}

		public CraftShopMedievalOneFloorWEAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CraftShopMedievalOneFloorWEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CraftShopMedievalOneFloorWEAddon();
			}
		}

		[Constructable]
		public CraftShopMedievalOneFloorWEAddonDeed()
		{
			Name = "CraftShopMedievalOneFloorWE";
		}

		public CraftShopMedievalOneFloorWEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}