/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CustomFrontageAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CustomFrontageAddonDeed();
			}
		}

		[ Constructable ]
		public CustomFrontageAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6050 );
			AddComponent( ac, -6, 4, 0 );
			ac = new AddonComponent( 6572 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 2, 5, 17 );
			ac = new AddonComponent( 3256 );
			AddComponent( ac, -2, 6, 2 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6044 );
			AddComponent( ac, -7, -1, 0 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, -9, -3, 0 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 0, 4, 4 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, -2, 1, 4 );
			ac = new AddonComponent( 3236 );
			AddComponent( ac, -11, -1, 0 );
			ac = new AddonComponent( 6057 );
			AddComponent( ac, -5, -1, 0 );
			ac = new AddonComponent( 1826 );
			AddComponent( ac, 0, 6, 0 );
			ac = new AddonComponent( 1998 );
			AddComponent( ac, 1, 5, 4 );
			ac = new AddonComponent( 6572 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 2, 1, 17 );
			ac = new AddonComponent( 1826 );
			AddComponent( ac, 1, 6, 0 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, 2, 5, 4 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, -2, 6, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 5, 0 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, -2, 5, 4 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, -10, -1, 0 );
			ac = new AddonComponent( 3344 );
			AddComponent( ac, -10, -3, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, -8, 1, 0 );
			ac = new AddonComponent( 3336 );
			AddComponent( ac, -6, 2, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, -5, 0, 0 );
			ac = new AddonComponent( 1999 );
			AddComponent( ac, 0, 1, 4 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -8, -1, 0 );
			ac = new AddonComponent( 6051 );
			AddComponent( ac, -11, -1, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, -9, 2, 0 );
			ac = new AddonComponent( 6587 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -2, 1, 14 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6587 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 2, 5, 14 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 6056 );
			AddComponent( ac, -8, 3, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 6050 );
			AddComponent( ac, 3, 6, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, -4, 5, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -5, 1, 0 );
			ac = new AddonComponent( 6044 );
			AddComponent( ac, -6, 1, 0 );
			ac = new AddonComponent( 3128 );
			AddComponent( ac, -9, 4, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 1, 1, 4 );
			ac = new AddonComponent( 6053 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, -6, -1, 0 );
			ac = new AddonComponent( 6572 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -2, 5, 17 );
			ac = new AddonComponent( 1828 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6056 );
			AddComponent( ac, 2, 6, 0 );
			ac = new AddonComponent( 3523 );
			AddComponent( ac, 2, 3, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, -9, -2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 5, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, 3, 5, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, -6, 0, 0 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 0, 3, 4 );
			ac = new AddonComponent( 1826 );
			AddComponent( ac, -1, 6, 0 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, -6, 2, 0 );
			ac = new AddonComponent( 6572 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -2, 1, 17 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, -3, 5, 0 );
			ac = new AddonComponent( 6059 );
			AddComponent( ac, -5, 4, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -9, 0, 0 );
			ac = new AddonComponent( 6052 );
			AddComponent( ac, -10, -3, 0 );
			ac = new AddonComponent( 6048 );
			AddComponent( ac, -6, -2, 0 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, -7, 1, 0 );
			ac = new AddonComponent( 6048 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 6811 );
			AddComponent( ac, -5, -1, 0 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 0, 2, 4 );
			ac = new AddonComponent( 3517 );
			AddComponent( ac, -4, 5, 1 );
			ac = new AddonComponent( 6056 );
			AddComponent( ac, -5, 6, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, -4, 6, 0 );
			ac = new AddonComponent( 6587 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -2, 5, 14 );
			ac = new AddonComponent( 3212 );
			AddComponent( ac, -3, 6, 1 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1998 );
			AddComponent( ac, 1, 2, 4 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -8, 0, 0 );
			ac = new AddonComponent( 3255 );
			AddComponent( ac, -7, 3, 1 );
			ac = new AddonComponent( 1999 );
			AddComponent( ac, -1, 3, 4 );
			ac = new AddonComponent( 1999 );
			AddComponent( ac, -1, 5, 4 );
			ac = new AddonComponent( 3339 );
			AddComponent( ac, -8, -1, 1 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, -8, -2, 0 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, -2, 5, 0 );
			ac = new AddonComponent( 1828 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6057 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 3141 );
			AddComponent( ac, -6, 6, 0 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, -2, 5, 8 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -7, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, 2, 5, 8 );
			ac = new AddonComponent( 1999 );
			AddComponent( ac, 1, 3, 4 );
			ac = new AddonComponent( 6057 );
			AddComponent( ac, -7, -2, 0 );
			ac = new AddonComponent( 6060 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 6059 );
			AddComponent( ac, -7, 3, 0 );
			ac = new AddonComponent( 3521 );
			AddComponent( ac, -3, 2, 1 );
			ac = new AddonComponent( 1998 );
			AddComponent( ac, -1, 1, 4 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 5, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, -5, 2, 0 );
			ac = new AddonComponent( 3207 );
			AddComponent( ac, -10, 2, 0 );
			ac = new AddonComponent( 6059 );
			AddComponent( ac, -8, 2, 0 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, -2, 1, 8 );
			ac = new AddonComponent( 9037 );
			AddComponent( ac, 3, -1, 1 );
			ac = new AddonComponent( 3389 );
			AddComponent( ac, -6, 1, 0 );
			ac = new AddonComponent( 6054 );
			AddComponent( ac, -10, -4, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 6050 );
			AddComponent( ac, -3, 6, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 3210 );
			AddComponent( ac, 3, 6, 0 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, 2, 1, 8 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6047 );
			AddComponent( ac, -9, -4, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -5, 3, 0 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, 2, 1, 4 );
			ac = new AddonComponent( 1998 );
			AddComponent( ac, -1, 4, 4 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 6054 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 0, 5, 4 );
			ac = new AddonComponent( 6044 );
			AddComponent( ac, -6, 3, 0 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, -1, 2, 4 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, -7, 0, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 6056 );
			AddComponent( ac, -7, 4, 0 );
			ac = new AddonComponent( 1828 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6587 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 2, 1, 14 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 6053 );
			AddComponent( ac, -5, -2, 0 );
			ac = new AddonComponent( 6052 );
			AddComponent( ac, -5, 5, 0 );
			ac = new AddonComponent( 6044 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 6054 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 5, 0 );
			ac = new AddonComponent( 3214 );
			AddComponent( ac, -5, 5, 1 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 1, 4, 4 );
			ac = new AddonComponent( 6044 );
			AddComponent( ac, -9, -1, 0 );
			ac = new AddonComponent( 6053 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, 2, 5, 0 );
			ac = new AddonComponent( 7883 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, -7, -3, 0 );
			ac = new AddonComponent( 6059 );
			AddComponent( ac, -10, 1, 0 );
			ac = new AddonComponent( 6052 );
			AddComponent( ac, -11, 0, 0 );
			ac = new AddonComponent( 6056 );
			AddComponent( ac, -11, 1, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, -9, 1, 0 );
			ac = new AddonComponent( 6056 );
			AddComponent( ac, -10, 2, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -8, -3, 0 );
			ac = new AddonComponent( 6060 );
			AddComponent( ac, -10, -2, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, -10, 0, 0 );
			ac = new AddonComponent( 6054 );
			AddComponent( ac, -11, -2, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 6044 );
			AddComponent( ac, 7, -1, 0 );
			ac = new AddonComponent( 6060 );
			AddComponent( ac, 7, -3, 0 );
			ac = new AddonComponent( 6044 );
			AddComponent( ac, 6, 0, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 8, -3, 0 );
			ac = new AddonComponent( 6044 );
			AddComponent( ac, 10, -2, 0 );
			ac = new AddonComponent( 6050 );
			AddComponent( ac, 7, 3, 0 );
			ac = new AddonComponent( 3232 );
			AddComponent( ac, 12, -1, 0 );
			ac = new AddonComponent( 3336 );
			AddComponent( ac, 10, -3, 1 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 4, 6, 0 );
			ac = new AddonComponent( 6060 );
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 6058 );
			AddComponent( ac, 10, 0, 0 );
			ac = new AddonComponent( 6058 );
			AddComponent( ac, 8, 1, 0 );
			ac = new AddonComponent( 6060 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 3380 );
			AddComponent( ac, 9, 2, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, 7, -2, 0 );
			ac = new AddonComponent( 6058 );
			AddComponent( ac, 6, 3, 0 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 10, 1, 0 );
			ac = new AddonComponent( 3376 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 3142 );
			AddComponent( ac, 5, 5, 0 );
			ac = new AddonComponent( 3237 );
			AddComponent( ac, 11, -5, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 6, 1, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 3338 );
			AddComponent( ac, 10, -3, 1 );
			ac = new AddonComponent( 3211 );
			AddComponent( ac, 12, -3, 1 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 9, -3, 0 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, 6, -1, 0 );
			ac = new AddonComponent( 6046 );
			AddComponent( ac, 12, -2, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 4, 5, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 7, 0, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 9, -4, 0 );
			ac = new AddonComponent( 6058 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, 8, 0, 0 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 8, -1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 11, -2, 0 );
			ac = new AddonComponent( 3515 );
			AddComponent( ac, 6, -1, 1 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 6, 4, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, 10, -3, 0 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, 9, 0, 0 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, 11, -3, 0 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, 7, 2, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 6, 4, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 7, 1, 0 );
			ac = new AddonComponent( 6053 );
			AddComponent( ac, 12, -4, 0 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, 10, -1, 0 );
			ac = new AddonComponent( 6054 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 3143 );
			AddComponent( ac, 10, 1, 0 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 8, 3, 0 );
			ac = new AddonComponent( 6048 );
			AddComponent( ac, 9, -5, 0 );
			ac = new AddonComponent( 6057 );
			AddComponent( ac, 11, -4, 0 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 12, -3, 0 );
			ac = new AddonComponent( 6044 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 3334 );
			AddComponent( ac, 7, 0, 1 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 3262 );
			AddComponent( ac, 11, 0, 1 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 11, 0, 0 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, 9, 1, 0 );
			ac = new AddonComponent( 6053 );
			AddComponent( ac, 11, -5, 0 );
			ac = new AddonComponent( 6044 );
			AddComponent( ac, 9, -1, 0 );
			ac = new AddonComponent( 6046 );
			AddComponent( ac, 8, 2, 0 );
			ac = new AddonComponent( 6044 );
			AddComponent( ac, 9, -2, 0 );
			ac = new AddonComponent( 6058 );
			AddComponent( ac, 11, -1, 0 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 6041 );
			AddComponent( ac, 10, -4, 0 );
			ac = new AddonComponent( 6049 );
			AddComponent( ac, 5, 4, 0 );
			ac = new AddonComponent( 3516 );
			AddComponent( ac, 5, 1, 1 );
			ac = new AddonComponent( 6047 );
			AddComponent( ac, 10, -5, 0 );
			ac = new AddonComponent( 6043 );
			AddComponent( ac, 8, -2, 0 );
			ac = new AddonComponent( 6040 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 12, -1, 0 );
			ac = new AddonComponent( 6047 );
			AddComponent( ac, 6, -3, 0 );
			ac = new AddonComponent( 6054 );
			AddComponent( ac, 5, -3, 0 );

		}

		public CustomFrontageAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CustomFrontageAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CustomFrontageAddon();
			}
		}

		[Constructable]
		public CustomFrontageAddonDeed()
		{
			Name = "CustomFrontage";
		}

		public CustomFrontageAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}