/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class D14PathtoKeepAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new D14PathtoKeepAddonDeed();
			}
		}

		[ Constructable ]
		public D14PathtoKeepAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, -6, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, -5, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, -6, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, -5, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -6, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -5, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -8, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -7, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -6, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -5, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, -9, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, -8, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, -7, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, -6, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, -5, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, -4, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 1928 );
			AddComponent( ac, 0, -7, 0 );
			ac = new AddonComponent( 1928 );
			AddComponent( ac, 1, -7, 0 );
			ac = new AddonComponent( 1929 );
			AddComponent( ac, 0, -6, 0 );
			ac = new AddonComponent( 1929 );
			AddComponent( ac, 1, -6, 0 );
			ac = new AddonComponent( 1931 );
			AddComponent( ac, 0, -8, 0 );
			ac = new AddonComponent( 1931 );
			AddComponent( ac, 1, -8, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, -8, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, -7, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, -6, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, -5, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, -6, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, -5, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, -4, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 3, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 1, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, -1, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, -3, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, -5, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, -7, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 3, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 1, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, -1, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, -3, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, -5, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, -7, 3 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, 5, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, 6, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, 7, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, 6, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, 7, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 5, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 6, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 7, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 5, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 6, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 7, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, 5, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, 6, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 2, 7, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 5, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 6, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 7, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 5, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 6, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 7, 0 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 7, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 7, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, -2, 5, 3 );
			ac = new AddonComponent( 490 );
			AddComponent( ac, 2, 5, 3 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, 8, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 8, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 1, 9, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, 0, 10, 0 );
			ac = new AddonComponent( 1316 );
			AddComponent( ac, -1, 9, 0 );
			ac = new AddonComponent( 6025 );
			AddComponent( ac, 1, 9, 0 );
			ac = new AddonComponent( 6025 );
			AddComponent( ac, 0, 10, 0 );
			ac = new AddonComponent( 6025 );
			AddComponent( ac, -1, 9, 0 );
			ac = new AddonComponent( 6025 );
			AddComponent( ac, 0, 8, 0 );
			ac = new AddonComponent( 6023 );
			AddComponent( ac, 2, 8, 1 );
			ac = new AddonComponent( 6022 );
			AddComponent( ac, 1, 8, 0 );

		}

		public D14PathtoKeepAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class D14PathtoKeepAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new D14PathtoKeepAddon();
			}
		}

		[Constructable]
		public D14PathtoKeepAddonDeed()
		{
			Name = "D14PathtoKeep";
		}

		public D14PathtoKeepAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}