/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DadsWorkTableNAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DadsWorkTableNAddonDeed();
			}
		}

		[ Constructable ]
		public DadsWorkTableNAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6790 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 4017 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 4021 );
			AddComponent( ac, -1, 0, 6 );
			ac = new AddonComponent( 6262 );
			AddComponent( ac, 0, 0, 6 );
			ac = new AddonComponent( 6787 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 2950 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2950 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6786 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 4015 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2946 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 4325 );
			AddComponent( ac, -1, 0, 6 );
			ac = new AddonComponent( 14133 );
			AddComponent( ac, -3, 0, 3 );
			ac = new AddonComponent( 4180 );
			AddComponent( ac, 2, 0, 6 );
			ac = new AddonComponent( 7129 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 2945 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 7865 );
			AddComponent( ac, 2, 0, 5 );
			ac = new AddonComponent( 4144 );
			AddComponent( ac, 3, 0, 6 );
			ac = new AddonComponent( 2950 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2463 );
			AddComponent( ac, 2, 1, 13 );

		}

		public DadsWorkTableNAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DadsWorkTableNAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DadsWorkTableNAddon();
			}
		}

		[Constructable]
		public DadsWorkTableNAddonDeed()
		{
			Name = "DadsWorkTableN";
		}

		public DadsWorkTableNAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}