
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DarkWoodenDrawbridgeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {933, -2, -4, 0}, {933, -2, 0, 0}, {933, -2, 4, 0}// 1	2	3	
			, {1993, -2, -4, 5}, {1993, -2, -3, 5}, {1993, -2, -2, 5}// 4	5	6	
			, {1993, -2, -1, 5}, {1993, -2, 0, 5}, {1993, -2, 1, 5}// 7	8	9	
			, {1993, -2, 2, 5}, {1993, -2, 3, 5}, {1993, -2, 4, 5}// 10	11	12	
			, {8760, -2, -2, 5}, {8760, -2, -3, 16}, {933, -2, -4, 7}// 22	23	24	
			, {933, -2, 4, 7}, {933, -2, 0, 7}, {933, 3, -4, 0}// 25	26	30	
			, {933, 3, 0, 0}, {933, 3, 4, 0}, {1993, -1, -4, 5}// 31	32	33	
			, {1993, -1, -2, 5}, {1993, -1, 0, 5}, {1993, -1, 2, 5}// 34	35	36	
			, {1993, -1, 4, 5}, {1993, 0, -4, 5}, {1993, 0, -3, 5}// 37	38	39	
			, {1993, 0, -1, 5}, {1993, 0, 0, 5}, {1993, 0, 1, 5}// 40	41	42	
			, {1993, 0, 3, 5}, {1993, 0, 4, 5}, {1993, 1, -3, 5}// 43	44	45	
			, {1993, 1, -2, 5}, {1993, 1, -1, 5}, {1993, 1, 1, 5}// 46	47	48	
			, {1993, 1, 2, 5}, {1993, 1, 3, 5}, {1993, 2, -4, 5}// 49	50	51	
			, {1993, 2, -2, 5}, {1993, 2, 0, 5}, {1993, 2, 2, 5}// 52	53	54	
			, {1993, 2, 4, 5}, {1993, 3, -4, 5}, {1993, 3, -3, 5}// 55	56	57	
			, {1993, 3, -2, 5}, {1993, 3, -1, 5}, {1993, 3, 0, 5}// 58	59	60	
			, {1993, 3, 1, 5}, {1993, 3, 2, 5}, {1993, 3, 3, 5}// 61	62	63	
			, {1993, 3, 4, 5}, {1996, 1, -4, 5}, {1996, 2, -3, 5}// 64	65	66	
			, {1996, -1, -3, 5}, {1996, 0, -2, 5}, {1996, -1, -1, 5}// 67	68	69	
			, {1996, 2, -1, 5}, {1996, 1, 0, 5}, {1996, 2, 1, 5}// 70	71	72	
			, {1996, -1, 1, 5}, {1996, 0, 2, 5}, {1996, 2, 3, 5}// 73	74	75	
			, {1996, -1, 3, 5}, {1996, 1, 4, 5}, {8760, 3, -2, 5}// 76	77	87	
			, {8760, 3, -3, 16}, {2171, -1, 5, 0}, {2171, 0, 5, 0}// 88	89	90	
			, {2171, 1, 5, 0}, {2171, 2, 5, 0}, {933, 3, 4, 7}// 91	92	93	
			, {933, 3, 0, 7}, {933, 3, -4, 7}// 94	95	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DarkWoodenDrawbridgeAddonDeed();
			}
		}

		[ Constructable ]
		public DarkWoodenDrawbridgeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 926, -3, -4, 5, 1869, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 926, -3, -3, 5, 1869, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 926, -3, -2, 5, 1869, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 926, -3, -1, 5, 1869, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 926, -3, 0, 5, 1869, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 926, -3, 1, 5, 1869, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 926, -3, 2, 5, 1869, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 926, -3, 3, 5, 1869, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 926, -3, 4, 5, 1869, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 6587, -2, -4, 13, 0, 10, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 6587, -2, 0, 13, 0, 10, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 6587, -2, 4, 13, 0, 10, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 926, 3, 4, 5, 1869, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 926, 3, -4, 5, 1869, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 926, 3, -3, 5, 1869, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 926, 3, -2, 5, 1869, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 926, 3, -1, 5, 1869, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 926, 3, 0, 5, 1869, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 926, 3, 1, 5, 1869, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 926, 3, 2, 5, 1869, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 926, 3, 3, 5, 1869, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 6587, 3, -4, 13, 0, 10, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 6587, 3, 0, 13, 0, 10, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 6587, 3, 4, 13, 0, 10, "", 1);// 98

		}

		public DarkWoodenDrawbridgeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DarkWoodenDrawbridgeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DarkWoodenDrawbridgeAddon();
			}
		}

		[Constructable]
		public DarkWoodenDrawbridgeAddonDeed()
		{
			Name = "DarkWoodenDrawbridge";
		}

		public DarkWoodenDrawbridgeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}