/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DarkElveThroneAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DarkElveThroneAddonDeed();
			}
		}

		[ Constructable ]
		public DarkElveThroneAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 3312 );
			ac.Hue = 956;
			AddComponent( ac, -2, 0, 2 );
			ac = new AddonComponent( 3312 );
			ac.Hue = 2572;
			AddComponent( ac, -2, 2, 2 );
			ac = new AddonComponent( 3312 );
			ac.Hue = 956;
			AddComponent( ac, -2, -2, 2 );
			ac = new AddonComponent( 4068 );
			ac.Hue = 2572;
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 3311 );
			ac.Hue = 2572;
			AddComponent( ac, -2, -2, 2 );
			ac = new AddonComponent( 3311 );
			ac.Hue = 2523;
			AddComponent( ac, -2, 2, 3 );
			ac = new AddonComponent( 4067 );
			ac.Hue = 2572;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 3311 );
			ac.Hue = 2523;
			AddComponent( ac, -2, -2, 3 );
			ac = new AddonComponent( 5499 );
			ac.Hue = 2540;
			AddComponent( ac, 2, -1, 2 );
			ac = new AddonComponent( 5499 );
			ac.Hue = 2540;
			AddComponent( ac, 2, 3, 2 );
			ac = new AddonComponent( 5469 );
			ac.Hue = 2572;
			AddComponent( ac, -1, -2, 2 );
			ac = new AddonComponent( 14089 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2551;
			AddComponent( ac, -1, 0, 2 );
			ac = new AddonComponent( 5468 );
			ac.Hue = 2572;
			AddComponent( ac, -1, 3, 2 );
			ac = new AddonComponent( 5415 );
			ac.Hue = 2572;
			AddComponent( ac, -1, 0, 2 );
			ac = new AddonComponent( 5414 );
			ac.Hue = 2572;
			AddComponent( ac, -1, 1, 2 );

		}

		public DarkElveThroneAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DarkElveThroneAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DarkElveThroneAddon();
			}
		}

		[Constructable]
		public DarkElveThroneAddonDeed()
		{
			Name = "DarkElveThrone";
		}

		public DarkElveThroneAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}
