
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class darkgardenshedAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new darkgardenshedAddonDeed();
			}
		}

		[ Constructable ]
		public darkgardenshedAddon()
		{



			AddComplexComponent( (BaseAddon) this, 664, 1, -2, 0, 2615, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 664, -1, -2, 0, 2615, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 660, -2, -2, 0, 2615, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 9534, 0, -2, 0, 2615, 1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 662, 1, 2, 0, 2615, 1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 662, 1, -1, 0, 2615, 1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 664, -1, 2, 0, 2615, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 664, 1, 2, 0, 2615, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 665, -2, -1, 0, 2615, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 665, -2, 0, 0, 2615, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 665, -2, 1, 0, 2615, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 665, -2, 2, 0, 2615, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1266, -1, -1, 0, 2615, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1266, -1, 0, 0, 2615, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1266, -1, 1, 0, 2615, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1266, -1, 2, 0, 2615, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1266, 0, -1, 0, 2615, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1266, 0, 0, 0, 2615, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1266, 0, 1, 0, 2615, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1266, 0, 2, 0, 2615, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1266, 1, -1, 0, 2615, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1266, 1, 0, 0, 2615, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1266, 1, 1, 0, 2615, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1266, 1, 2, 0, 2615, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 9534, 0, 2, 0, 2615, 1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 10515, 2, -1, 20, 2605, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 10515, 1, -1, 20, 2605, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 10515, 0, -1, 20, 2605, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 10515, -1, -1, 20, 2605, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 10509, -1, 3, 21, 2605, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 10509, 0, 3, 21, 2605, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 10509, 1, 3, 21, 2605, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 10509, 2, 3, 21, 2605, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 10508, -1, 2, 24, 2605, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 10508, 0, 2, 24, 2605, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 10508, 1, 2, 24, 2605, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 10508, 2, 2, 24, 2605, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 10514, -1, 0, 23, 2605, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 10514, 0, 0, 23, 2605, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 10514, 1, 0, 23, 2605, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 10514, 2, 0, 23, 2605, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 10507, -1, 1, 27, 2605, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 10507, 0, 1, 27, 2605, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 10507, 1, 1, 27, 2605, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 10507, 2, 1, 27, 2605, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 691, 1, 1, 0, 2615, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 692, 1, 0, 0, 2615, -1, "", 1);// 47

		}

		public darkgardenshedAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class darkgardenshedAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new darkgardenshedAddon();
			}
		}

		[Constructable]
		public darkgardenshedAddonDeed()
		{
			Name = "darkgardenshed";
		}

		public darkgardenshedAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}