/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DarkBedAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DarkBedAddonDeed();
			}
		}

		[ Constructable ]
		public DarkBedAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 4845 );
			ac.Hue = 2510;
			AddComponent( ac, -1, -3, 1 );
			ac = new AddonComponent( 4845 );
			ac.Hue = 2510;
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 2783 );
			ac.Hue = 2510;
			AddComponent( ac, -3, -1, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 1, -2, 1 );
			ac = new AddonComponent( 1 );
			ac.Hue = 2510;
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 4831 );
			ac.Hue = 2510;
			AddComponent( ac, 3, -2, 1 );
			ac = new AddonComponent( 2786 );
			ac.Hue = 2510;
			AddComponent( ac, -2, 2, 1 );
			ac = new AddonComponent( 7742 );
			ac.Hue = 2500;
			AddComponent( ac, -1, 0, 3 );
			ac = new AddonComponent( 2786 );
			ac.Hue = 2510;
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 2691 );
			ac.Hue = 2510;
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 2783 );
			ac.Hue = 2510;
			AddComponent( ac, -3, -2, 1 );
			ac = new AddonComponent( 7736 );
			ac.Hue = 2500;
			AddComponent( ac, -1, 2, 3 );
			ac = new AddonComponent( 3205 );
			AddComponent( ac, -2, -2, 17 );
			ac = new AddonComponent( 2687 );
			ac.Hue = 2510;
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 2781 );
			ac.Hue = 2510;
			AddComponent( ac, -3, 2, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -2, -1, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 4843 );
			ac.Hue = 2510;
			AddComponent( ac, -2, 3, 1 );
			ac = new AddonComponent( 9245 );
			AddComponent( ac, -2, -2, 13 );
			ac = new AddonComponent( 4845 );
			ac.Hue = 2510;
			AddComponent( ac, 2, -3, 1 );
			ac = new AddonComponent( 4834 );
			ac.Hue = 2510;
			AddComponent( ac, 3, -1, 1 );
			ac = new AddonComponent( 7737 );
			ac.Hue = 2500;
			AddComponent( ac, -1, 1, 3 );
			ac = new AddonComponent( 4831 );
			ac.Hue = 2510;
			AddComponent( ac, 3, 3, 1 );
			ac = new AddonComponent( 2779 );
			ac.Hue = 2510;
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 7740 );
			ac.Hue = 2500;
			AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 7734 );
			ac.Hue = 2500;
			AddComponent( ac, 1, 2, 3 );
			ac = new AddonComponent( 9245 );
			AddComponent( ac, -2, -2, 13 );
			ac = new AddonComponent( 2779 );
			ac.Hue = 2510;
			AddComponent( ac, 2, 2, 1 );
			ac = new AddonComponent( 2780 );
			ac.Hue = 2510;
			AddComponent( ac, -3, -3, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 2783 );
			ac.Hue = 2510;
			AddComponent( ac, -3, -2, 1 );
			ac = new AddonComponent( 2784 );
			ac.Hue = 2510;
			AddComponent( ac, -2, -3, 1 );
			ac = new AddonComponent( 7739 );
			ac.Hue = 2500;
			AddComponent( ac, 1, 1, 3 );
			ac = new AddonComponent( 2784 );
			ac.Hue = 2510;
			AddComponent( ac, -1, -3, 1 );
			ac = new AddonComponent( 2785 );
			ac.Hue = 2510;
			AddComponent( ac, 2, -2, 1 );
			ac = new AddonComponent( 2786 );
			ac.Hue = 2510;
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 2784 );
			ac.Hue = 2510;
			AddComponent( ac, 0, -3, 1 );
			ac = new AddonComponent( 7741 );
			ac.Hue = 2500;
			AddComponent( ac, 0, 0, 3 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 2785 );
			ac.Hue = 2510;
			AddComponent( ac, 2, -2, 1 );
			ac = new AddonComponent( 7735 );
			ac.Hue = 2500;
			AddComponent( ac, 0, 2, 3 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 1 );
			ac.Hue = 2500;
			AddComponent( ac, 0, 1, 3 );
			ac = new AddonComponent( 2782 );
			ac.Hue = 2510;
			AddComponent( ac, 2, -3, 1 );
			ac = new AddonComponent( 2785 );
			ac.Hue = 2510;
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 4831 );
			ac.Hue = 2510;
			AddComponent( ac, -3, -2, 1 );
			ac = new AddonComponent( 2786 );
			ac.Hue = 2510;
			AddComponent( ac, -1, 2, 1 );
			ac = new AddonComponent( 2786 );
			ac.Hue = 2510;
			AddComponent( ac, -1, 2, 1 );
			ac = new AddonComponent( 2781 );
			ac.Hue = 2510;
			AddComponent( ac, -3, 2, 1 );
			ac = new AddonComponent( 2783 );
			ac.Hue = 2510;
			AddComponent( ac, -3, -1, 1 );
			ac = new AddonComponent( 2786 );
			ac.Hue = 2510;
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 2785 );
			ac.Hue = 2510;
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 1 );
			ac.Hue = 2510;
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 2785 );
			ac.Hue = 2510;
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -2, 0, 1 );
			ac = new AddonComponent( 2784 );
			ac.Hue = 2510;
			AddComponent( ac, -1, -3, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 2783 );
			ac.Hue = 2510;
			AddComponent( ac, -3, 1, 1 );
			ac = new AddonComponent( 2786 );
			ac.Hue = 2510;
			AddComponent( ac, -2, 2, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 4834 );
			ac.Hue = 2510;
			AddComponent( ac, -3, -1, 1 );
			ac = new AddonComponent( 3205 );
			AddComponent( ac, -2, -2, 17 );
			ac = new AddonComponent( 2783 );
			ac.Hue = 2510;
			AddComponent( ac, -3, 1, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -2, -1, 1 );
			ac = new AddonComponent( 4834 );
			ac.Hue = 2510;
			AddComponent( ac, -3, 2, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 7738 );
			ac.Hue = 2500;
			AddComponent( ac, 0, 1, 3 );
			ac = new AddonComponent( 2780 );
			ac.Hue = 2510;
			AddComponent( ac, -3, -3, 1 );
			ac = new AddonComponent( 2785 );
			ac.Hue = 2510;
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 4845 );
			ac.Hue = 2510;
			AddComponent( ac, -1, 3, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -2, -2, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 4834 );
			ac.Hue = 2510;
			AddComponent( ac, 3, 2, 1 );
			ac = new AddonComponent( 2784 );
			ac.Hue = 2510;
			AddComponent( ac, 0, -3, 1 );
			ac = new AddonComponent( 3265 );
			AddComponent( ac, -1, -1, 29 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -2, 0, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 1, -2, 1 );
			ac = new AddonComponent( 2785 );
			ac.Hue = 2510;
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 2785 );
			ac.Hue = 2510;
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 2783 );
			ac.Hue = 2510;
			AddComponent( ac, -3, 0, 1 );
			ac = new AddonComponent( 2784 );
			ac.Hue = 2510;
			AddComponent( ac, 1, -3, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 4831 );
			ac.Hue = 2510;
			AddComponent( ac, -3, 3, 1 );
			ac = new AddonComponent( 2782 );
			ac.Hue = 2510;
			AddComponent( ac, 2, -3, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 2783 );
			ac.Hue = 2510;
			AddComponent( ac, -3, 0, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -2, -2, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 11763 );
			ac.Hue = 2511;
			AddComponent( ac, -2, -2, 6 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 4843 );
			ac.Hue = 2510;
			AddComponent( ac, -2, -3, 1 );
			ac = new AddonComponent( 1 );
			AddComponent( ac, -2, -2, 13 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 2690 );
			ac.Hue = 2510;
			AddComponent( ac, 0, -2, 1 );
			ac = new AddonComponent( 9036 );
			AddComponent( ac, -1, -1, 30 );
			ac = new AddonComponent( 2786 );
			ac.Hue = 2510;
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 4843 );
			ac.Hue = 2510;
			AddComponent( ac, 3, -3, 1 );
			ac = new AddonComponent( 2686 );
			ac.Hue = 2510;
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 2784 );
			ac.Hue = 2510;
			AddComponent( ac, 1, -3, 1 );
			ac = new AddonComponent( 2784 );
			ac.Hue = 2510;
			AddComponent( ac, -2, -3, 1 );
			ac = new AddonComponent( 2778 );
			ac.Hue = 2510;
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 4843 );
			ac.Hue = 2510;
			AddComponent( ac, 3, 3, 1 );

		}

		public DarkBedAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DarkBedAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DarkBedAddon();
			}
		}

		[Constructable]
		public DarkBedAddonDeed()
		{
			Name = "DarkBed";
		}

		public DarkBedAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}