
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class decolamp3Addon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new decolamp3AddonDeed();
			}
		}

		[ Constructable ]
		public decolamp3Addon()
		{



			AddComplexComponent( (BaseAddon) this, 2848, 0, 0, 0, 2785, 1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 4235, 0, 0, 13, 2352, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 4235, 0, 0, 10, 2352, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 4235, 0, 0, 7, 2352, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 4235, 0, 0, 4, 2352, -1, "", 1);// 5

		}

		public decolamp3Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class decolamp3AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new decolamp3Addon();
			}
		}

		[Constructable]
		public decolamp3AddonDeed()
		{
			Name = "decolamp3";
		}

		public decolamp3AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}