/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DKWoodKitchenWEAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DKWoodKitchenWEAddonDeed();
			}
		}

		[ Constructable ]
		public DKWoodKitchenWEAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -6, -4, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -6, -3, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -6, -2, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -5, -4, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -4, -4, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -3, -4, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -6, -4, 5 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -6, -4, 10 );
			ac = new AddonComponent( 10331 );
			ac.Hue = 1036;
			AddComponent( ac, -3, -4, 11 );
			ac = new AddonComponent( 10331 );
			ac.Hue = 1036;
			AddComponent( ac, -4, -4, 11 );
			ac = new AddonComponent( 10331 );
			ac.Hue = 1036;
			AddComponent( ac, -5, -4, 11 );
			ac = new AddonComponent( 10332 );
			ac.Hue = 1036;
			AddComponent( ac, -6, -3, 11 );
			ac = new AddonComponent( 10332 );
			ac.Hue = 1036;
			AddComponent( ac, -6, -2, 11 );
			ac = new AddonComponent( 4104 );
			AddComponent( ac, -5, -4, 5 );
			ac = new AddonComponent( 4100 );
			AddComponent( ac, -5, -4, 9 );
			ac = new AddonComponent( 6420 );
			ac.Hue = 1367;
			AddComponent( ac, -4, -4, 5 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1899;
			AddComponent( ac, -6, -1, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1899;
			AddComponent( ac, -6, 0, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 2519 );
			ac.Hue = 1175;
			AddComponent( ac, -6, 0, 5 );
			ac = new AddonComponent( 2519 );
			ac.Hue = 1175;
			AddComponent( ac, -6, -1, 5 );
			ac = new AddonComponent( 6572 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -6, 0, 6 );
			ac = new AddonComponent( 6572 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -6, -1, 6 );
			ac = new AddonComponent( 7979 );
			AddComponent( ac, -6, 0, 6 );
			ac = new AddonComponent( 2541 );
			AddComponent( ac, -6, -1, 6 );
			ac = new AddonComponent( 3131 );
			AddComponent( ac, -6, -1, 5 );
			ac = new AddonComponent( 3133 );
			AddComponent( ac, -6, 0, 5 );
			ac = new AddonComponent( 3135 );
			AddComponent( ac, -6, 0, 5 );
			ac = new AddonComponent( 1 );
			AddComponent( ac, -3, -1, 5 );
			ac = new AddonComponent( 2449 );
			AddComponent( ac, -3, -1, 5 );
			ac = new AddonComponent( 7711 );
			AddComponent( ac, -3, -1, 5 );
			ac = new AddonComponent( 7711 );
			AddComponent( ac, -3, -1, 6 );
			ac = new AddonComponent( 2550 );
			AddComponent( ac, -3, -1, 6 );
			ac = new AddonComponent( 2449 );
			AddComponent( ac, -3, -1, 5 );
			ac = new AddonComponent( 7711 );
			AddComponent( ac, -3, -1, 5 );
			ac = new AddonComponent( 7711 );
			AddComponent( ac, -3, -1, 6 );
			ac = new AddonComponent( 2550 );
			AddComponent( ac, -3, -1, 6 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -6, 1, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -6, 2, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -6, 3, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -6, 4, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -6, 4, 5 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -6, 4, 10 );
			ac = new AddonComponent( 5738 );
			AddComponent( ac, -5, 4, 0 );
			ac = new AddonComponent( 5740 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -3, 4, 5 );
			ac = new AddonComponent( 10332 );
			ac.Hue = 1036;
			AddComponent( ac, -6, 3, 11 );
			ac = new AddonComponent( 10332 );
			ac.Hue = 1036;
			AddComponent( ac, -6, 2, 11 );
			ac = new AddonComponent( 11599 );
			AddComponent( ac, -4, 4, 9 );
			ac = new AddonComponent( 1 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 2903 );
			ac.Hue = 1036;
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 2903 );
			ac.Hue = 1036;
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 11525 );
			ac.Hue = 1153;
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 2519 );
			ac.Hue = 1428;
			AddComponent( ac, 4, -2, 6 );
			ac = new AddonComponent( 2519 );
			ac.Hue = 1428;
			AddComponent( ac, 3, -2, 6 );
			ac = new AddonComponent( 2494 );
			AddComponent( ac, 4, -2, 7 );
			ac = new AddonComponent( 2494 );
			AddComponent( ac, 3, -2, 7 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1 );
			ac.Hue = 1036;
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 2949 );
			ac.Hue = 1036;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 2949 );
			ac.Hue = 1036;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 2902 );
			ac.Hue = 1036;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 9440 );
			AddComponent( ac, -2, 0, 5 );
			ac = new AddonComponent( 2519 );
			ac.Hue = 1428;
			AddComponent( ac, 2, -1, 6 );
			ac = new AddonComponent( 2519 );
			ac.Hue = 1428;
			AddComponent( ac, 4, 0, 6 );
			ac = new AddonComponent( 2519 );
			ac.Hue = 1428;
			AddComponent( ac, 3, 0, 6 );
			ac = new AddonComponent( 2516 );
			AddComponent( ac, 3, 0, 7 );
			ac = new AddonComponent( 2516 );
			AddComponent( ac, 3, 0, 7 );
			ac = new AddonComponent( 2516 );
			AddComponent( ac, 4, 0, 7 );
			ac = new AddonComponent( 2493 );
			AddComponent( ac, 2, -1, 7 );
			ac = new AddonComponent( 10304 );
			AddComponent( ac, 4, -1, 6 );
			ac = new AddonComponent( 2537 );
			AddComponent( ac, 3, -1, 6 );
			ac = new AddonComponent( 2947 );
			ac.Hue = 1036;
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 2947 );
			ac.Hue = 1036;
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 2903 );
			ac.Hue = 1036;
			AddComponent( ac, 5, -3, 0 );
			ac = new AddonComponent( 2519 );
			ac.Hue = 1428;
			AddComponent( ac, 5, -2, 6 );
			ac = new AddonComponent( 2494 );
			AddComponent( ac, 5, -2, 7 );
			ac = new AddonComponent( 2948 );
			ac.Hue = 1036;
			AddComponent( ac, 6, 0, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 2951 );
			ac.Hue = 1036;
			AddComponent( ac, 6, -1, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 2950 );
			ac.Hue = 1036;
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 2948 );
			ac.Hue = 1036;
			AddComponent( ac, 6, 0, 0 );
			ac = new AddonComponent( 2951 );
			ac.Hue = 1036;
			AddComponent( ac, 6, -1, 0 );
			ac = new AddonComponent( 2519 );
			ac.Hue = 1428;
			AddComponent( ac, 6, -1, 6 );
			ac = new AddonComponent( 2519 );
			ac.Hue = 1428;
			AddComponent( ac, 5, 0, 6 );
			ac = new AddonComponent( 2516 );
			AddComponent( ac, 5, 0, 7 );
			ac = new AddonComponent( 2517 );
			AddComponent( ac, 6, -1, 7 );
			ac = new AddonComponent( 2429 );
			AddComponent( ac, 5, -1, 6 );
			ac = new AddonComponent( 2904 );
			ac.Hue = 1036;
			AddComponent( ac, 7, -1, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 1036;
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 2905 );
			ac.Hue = 1036;
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 2905 );
			ac.Hue = 1036;
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 4555 );
			AddComponent( ac, -2, 4, 5 );
			ac = new AddonComponent( 3169 );
			AddComponent( ac, -2, 4, 10 );
			ac = new AddonComponent( 2905 );
			ac.Hue = 1036;
			AddComponent( ac, 5, 1, 0 );

		}

		public DKWoodKitchenWEAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DKWoodKitchenWEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DKWoodKitchenWEAddon();
			}
		}

		[Constructable]
		public DKWoodKitchenWEAddonDeed()
		{
			Name = "DKWoodKitchenWE";
		}

		public DKWoodKitchenWEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}