/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DKWoodBridgeNSAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DKWoodBridgeNSAddonDeed();
			}
		}

		[ Constructable ]
		public DKWoodBridgeNSAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 2183 );
			AddComponent( ac, 0, 2, 12 );
			ac = new AddonComponent( 2184 );
			AddComponent( ac, 2, -5, 2 );
			ac = new AddonComponent( 2182 );
			AddComponent( ac, 2, 1, 12 );
			ac = new AddonComponent( 2182 );
			AddComponent( ac, 2, -3, 7 );
			ac = new AddonComponent( 2185 );
			AddComponent( ac, 0, -1, 7 );
			ac = new AddonComponent( 2180 );
			AddComponent( ac, 0, 3, 7 );
			ac = new AddonComponent( 2183 );
			AddComponent( ac, 0, 0, 12 );
			ac = new AddonComponent( 2184 );
			AddComponent( ac, -1, -5, 2 );
			ac = new AddonComponent( 2182 );
			AddComponent( ac, 2, 2, 12 );
			ac = new AddonComponent( 2182 );
			AddComponent( ac, 2, -2, 7 );
			ac = new AddonComponent( 2183 );
			AddComponent( ac, 0, 1, 12 );
			ac = new AddonComponent( 2183 );
			AddComponent( ac, 0, -2, 7 );
			ac = new AddonComponent( 2182 );
			AddComponent( ac, 2, 0, 12 );
			ac = new AddonComponent( 2183 );
			AddComponent( ac, 0, -3, 7 );
			ac = new AddonComponent( 2183 );
			AddComponent( ac, 0, -4, 7 );
			ac = new AddonComponent( 2181 );
			AddComponent( ac, 2, 3, 7 );
			ac = new AddonComponent( 2184 );
			AddComponent( ac, 2, -1, 7 );
			ac = new AddonComponent( 1851 );
			AddComponent( ac, 0, -5, 0 );
			ac = new AddonComponent( 1851 );
			AddComponent( ac, 1, -5, 0 );
			ac = new AddonComponent( 1851 );
			AddComponent( ac, 2, -5, 0 );
			ac = new AddonComponent( 1851 );
			AddComponent( ac, 0, -1, 5 );
			ac = new AddonComponent( 1851 );
			AddComponent( ac, 1, -1, 5 );
			ac = new AddonComponent( 1851 );
			AddComponent( ac, 2, -1, 5 );
			ac = new AddonComponent( 1849 );
			AddComponent( ac, 0, 3, 6 );
			ac = new AddonComponent( 1849 );
			AddComponent( ac, 1, 3, 6 );
			ac = new AddonComponent( 1849 );
			AddComponent( ac, 2, 3, 6 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 0, 0, 10 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 0, 1, 10 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 0, 2, 10 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 1, 0, 10 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 1, 1, 10 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 1, 2, 10 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 2, 0, 10 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 2, 1, 10 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 2, 2, 10 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 0, -4, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 0, -3, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 0, -2, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 1, -4, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 1, -3, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 1, -2, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 2, -4, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 2, -3, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 2, -2, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 0, 3, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 1, 3, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 2, 3, 5 );
			ac = new AddonComponent( 2182 );
			AddComponent( ac, 2, -4, 7 );
			ac = new AddonComponent( 2182 );
			AddComponent( ac, 2, 5, 7 );
			ac = new AddonComponent( 2183 );
			AddComponent( ac, 0, 5, 7 );
			ac = new AddonComponent( 2180 );
			AddComponent( ac, 0, 6, 2 );
			ac = new AddonComponent( 2181 );
			AddComponent( ac, 2, 6, 2 );
			ac = new AddonComponent( 2182 );
			AddComponent( ac, 2, 4, 7 );
			ac = new AddonComponent( 2183 );
			AddComponent( ac, 0, 4, 7 );
			ac = new AddonComponent( 1849 );
			AddComponent( ac, 0, 6, 0 );
			ac = new AddonComponent( 1849 );
			AddComponent( ac, 1, 6, 0 );
			ac = new AddonComponent( 1849 );
			AddComponent( ac, 2, 6, 0 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 0, 4, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 0, 5, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 1, 4, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 1, 5, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 2, 4, 5 );
			ac = new AddonComponent( 1997 );
			AddComponent( ac, 2, 5, 5 );

		}

		public DKWoodBridgeNSAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DKWoodBridgeNSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DKWoodBridgeNSAddon();
			}
		}

		[Constructable]
		public DKWoodBridgeNSAddonDeed()
		{
			Name = "DKWoodBridgeNS";
		}

		public DKWoodBridgeNSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}