
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class elvenwoodendloortileAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11579, -1, -1, 0}, {11579, -1, 0, 0}, {11579, -1, 1, 0}// 1	2	3	
			, {11579, -1, 2, 0}, {11579, 0, -1, 0}, {11579, 0, 0, 0}// 4	5	6	
			, {11579, 0, 1, 0}, {11579, 0, 2, 0}, {11579, 1, -1, 0}// 7	8	9	
			, {11579, 1, 0, 0}, {11579, 1, 1, 0}, {11579, 1, 2, 0}// 10	11	12	
			, {11579, 2, -1, 0}, {11579, 2, 0, 0}, {11579, 2, 1, 0}// 13	14	15	
			, {11579, 2, 2, 0}// 16	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new elvenwoodendloortileAddonDeed();
			}
		}

		[ Constructable ]
		public elvenwoodendloortileAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public elvenwoodendloortileAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class elvenwoodendloortileAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new elvenwoodendloortileAddon();
			}
		}

		[Constructable]
		public elvenwoodendloortileAddonDeed()
		{
			Name = "elvenwoodendloortile";
		}

		public elvenwoodendloortileAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}