
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class graveyard5NSAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {230, -1, -4, 0}, {231, -2, -3, 0}, {223, -2, -4, 0}// 1	2	3	
			, {231, -2, -3, 3}, {230, -1, -4, 3}, {223, -2, -4, 2}// 4	5	6	
			, {231, -2, -1, 0}, {227, -2, -3, 6}, {3326, -1, -3, 0}// 7	8	9	
			, {4461, -1, -1, 0}, {227, -2, 1, 0}, {231, -2, 0, 0}// 10	12	13	
			, {231, -2, 3, 0}, {231, -2, 4, 0}, {224, -1, 4, 0}// 14	15	16	
			, {231, -2, 4, 3}, {226, -2, 3, 3}, {3247, -1, 2, 0}// 17	18	19	
			, {3805, -1, 2, 0}, {6938, -1, 3, 0}, {4465, -1, 0, 0}// 20	21	22	
			, {224, 0, -4, 0}, {231, 3, -2, 0}, {231, 3, -1, 0}// 23	24	25	
			, {226, 3, -3, 0}, {226, 3, -1, 3}, {3317, 0, -3, 0}// 26	27	28	
			, {3318, 1, -3, 0}, {3319, 2, -3, 0}, {3245, 2, -3, 0}// 29	30	31	
			, {3245, 1, -3, 0}, {3808, 1, -1, 0}, {3810, 0, -1, 0}// 32	33	34	
			, {6921, 1, -1, 0}, {6934, 2, -1, 0}, {3145, 0, -2, 0}// 35	37	38	
			, {231, 3, 0, 0}, {231, 3, 4, 0}, {227, 3, 0, 3}// 39	40	41	
			, {3388, 0, 4, 0}, {3248, 3, 5, 0}, {3790, 3, 3, 0}// 42	43	44	
			, {3810, 0, 2, 0}, {3808, 1, 2, 0}, {3810, 0, 0, 0}// 45	46	47	
			, {3808, 1, 0, 0}, {6935, 1, 4, 0}, {6883, 0, 2, 2}// 48	49	50	
			, {3267, 2, 1, 0}, {3144, 2, 2, 0}// 51	52	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new graveyard5NSAddonDeed();
			}
		}

		[ Constructable ]
		public graveyard5NSAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6659, -1, -2, 3, 2852, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 6660, 0, -3, 5, 2450, -1, "", 1);// 36

		}

		public graveyard5NSAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class graveyard5NSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new graveyard5NSAddon();
			}
		}

		[Constructable]
		public graveyard5NSAddonDeed()
		{
			Name = "graveyard5NS";
		}

		public graveyard5NSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}