/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Hall2011CouchSAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Hall2011CouchSAddonDeed();
			}
		}

		[ Constructable ]
		public Hall2011CouchSAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 4632 );
			ac.Hue = 2694;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 4632 );
			ac.Hue = 2694;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 4632 );
			ac.Hue = 2694;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 2670;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1848 );
			ac.Hue = 2670;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 16141 );
			ac.Hue = 2694;
			AddComponent( ac, -2, 0, 5 );
			ac = new AddonComponent( 16141 );
			ac.Hue = 2694;
			AddComponent( ac, 2, 0, 5 );

		}

		public Hall2011CouchSAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Hall2011CouchSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Hall2011CouchSAddon();
			}
		}

		[Constructable]
		public Hall2011CouchSAddonDeed()
		{
			Name = "Hall2011CouchS";
		}

		public Hall2011CouchSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}