
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class hohohoneonNSAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new hohohoneonNSAddonDeed();
			}
		}

		[ Constructable ]
		public hohohoneonNSAddon()
		{



			AddComplexComponent( (BaseAddon) this, 7888, -11, -1, 0, 38, 2, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 7888, -11, -2, 0, 38, 2, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 7888, -9, -1, 0, 38, 2, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 7888, -9, -2, 0, 38, 2, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 7888, -7, -1, 0, 164, 2, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 7888, -7, -2, 0, 164, 2, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 7888, -6, -2, 0, 164, 2, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 7888, -11, 2, 0, 38, 2, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 7888, -11, 1, 0, 38, 2, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 7888, -11, 0, 0, 38, 2, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 7888, -10, 0, 0, 38, 2, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 7888, -9, 2, 0, 38, 2, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 7888, -9, 1, 0, 38, 2, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 7888, -9, 0, 0, 38, 2, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 7888, -7, 2, 0, 164, 2, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 7888, -7, 1, 0, 164, 2, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 7888, -7, 0, 0, 164, 2, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 7888, -6, 2, 0, 164, 2, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 7888, -5, -2, 0, 164, 2, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 7888, -5, -1, 0, 164, 2, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 7888, -3, -1, 0, 38, 2, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 7888, -3, -2, 0, 38, 2, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 7888, -1, -1, 0, 38, 2, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 7888, -1, -2, 0, 38, 2, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 7888, 1, -1, 0, 164, 2, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 7888, 1, -2, 0, 164, 2, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 7888, 3, -2, 0, 164, 2, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 7888, 3, -1, 0, 164, 2, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 7888, 2, -2, 0, 164, 2, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 7888, 5, -1, 0, 38, 2, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 7888, 5, -2, 0, 38, 2, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 7888, 7, -1, 0, 38, 2, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 7888, 7, -2, 0, 38, 2, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 7888, 10, -2, 0, 164, 2, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 7888, 9, -2, 0, 164, 2, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 7888, 9, -1, 0, 164, 2, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 7888, -5, 0, 0, 164, 2, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 7888, -5, 2, 0, 164, 2, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 7888, -5, 1, 0, 164, 2, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 7888, -3, 2, 0, 38, 2, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 7888, -3, 1, 0, 38, 2, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 7888, -3, 0, 0, 38, 2, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 7888, -2, 0, 0, 38, 2, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 7888, -1, 0, 0, 38, 2, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 7888, -1, 1, 0, 38, 2, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 7888, -1, 2, 0, 38, 2, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 7888, 1, 2, 0, 164, 2, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 7888, 1, 1, 0, 164, 2, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 7888, 1, 0, 0, 164, 2, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 7888, 3, 0, 0, 164, 2, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 7888, 3, 1, 0, 164, 2, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 7888, 2, 2, 0, 164, 2, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 7888, 5, 2, 0, 38, 2, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 7888, 5, 1, 0, 38, 2, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 7888, 5, 0, 0, 38, 2, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 7888, 6, 0, 0, 38, 2, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 7888, 7, 0, 0, 38, 2, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 7888, 7, 1, 0, 38, 2, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 7888, 7, 2, 0, 38, 2, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 7888, 9, 2, 0, 164, 2, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 7888, 10, 2, 0, 164, 2, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 7888, 9, 0, 0, 164, 2, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 7888, 9, 1, 0, 164, 2, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 7888, 3, 2, 0, 164, 2, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 7888, 11, -1, 0, 164, 2, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 7888, 11, -2, 0, 164, 2, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 7888, 11, 2, 0, 164, 2, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 7888, 11, 1, 0, 164, 2, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 7888, 11, 0, 0, 164, 2, "", 1);// 69

		}

		public hohohoneonNSAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class hohohoneonNSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new hohohoneonNSAddon();
			}
		}

		[Constructable]
		public hohohoneonNSAddonDeed()
		{
			Name = "hohohoneonNS";
		}

		public hohohoneonNSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}