/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class IllusionHouseTurqoiseAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new IllusionHouseTurqoiseAddonDeed();
			}
		}

		[ Constructable ]
		public IllusionHouseTurqoiseAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 10663 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 13932 );
			ac.Hue = 2670;
			AddComponent( ac, -2, -2, 29 );
			ac = new AddonComponent( 8170 );
			ac.Light = LightType.ArchedWindowEast;
			ac.Hue = 2670;
			AddComponent( ac, -4, -4, 6 );
			ac = new AddonComponent( 490 );
			ac.Hue = 2670;
			AddComponent( ac, -6, -5, 1 );
			ac = new AddonComponent( 1303 );
			ac.Hue = 2670;
			AddComponent( ac, -4, -4, 1 );
			ac = new AddonComponent( 10667 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 465 );
			ac.Hue = 2670;
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 10667 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 466 );
			ac.Hue = 2670;
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 491 );
			ac.Hue = 2692;
			AddComponent( ac, -6, -6, 1 );
			ac = new AddonComponent( 490 );
			ac.Hue = 2670;
			AddComponent( ac, -6, -4, 1 );
			ac = new AddonComponent( 465 );
			ac.Hue = 2670;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 463 );
			ac.Hue = 2670;
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 489 );
			ac.Hue = 2670;
			AddComponent( ac, -5, -6, 1 );
			ac = new AddonComponent( 2211 );
			ac.Hue = 2670;
			AddComponent( ac, -1, 0, 20 );
			ac = new AddonComponent( 1303 );
			ac.Hue = 1175;
			AddComponent( ac, -5, -5, 1 );
			ac = new AddonComponent( 10667 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 463 );
			ac.Hue = 2670;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 466 );
			ac.Hue = 2670;
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 464 );
			ac.Hue = 2670;
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 489 );
			ac.Hue = 2670;
			AddComponent( ac, -4, -6, 1 );
			ac = new AddonComponent( 1303 );
			ac.Hue = 2670;
			AddComponent( ac, -4, -5, 1 );
			ac = new AddonComponent( 1303 );
			ac.Hue = 2670;
			AddComponent( ac, -5, -4, 1 );
			ac = new AddonComponent( 10667 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 10663 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 10663 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 2, 6, 0 );
			ac = new AddonComponent( 2208 );
			ac.Hue = 2670;
			AddComponent( ac, 2, 1, 20 );
			ac = new AddonComponent( 2572 );
			ac.Light = LightType.ArchedWindowEast;
			ac.Hue = 2670;
			AddComponent( ac, 2, 7, 13 );
			ac = new AddonComponent( 10667 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 464 );
			ac.Hue = 2670;
			AddComponent( ac, 2, 6, 0 );
			ac = new AddonComponent( 466 );
			ac.Hue = 2670;
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 10663 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 464 );
			ac.Hue = 2670;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 1, 7, 0 );
			ac = new AddonComponent( 10663 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 10663 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 2, 7, 0 );
			ac = new AddonComponent( 463 );
			ac.Hue = 2670;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 2, 5, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 1, 6, 0 );
			ac = new AddonComponent( 10663 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 466 );
			ac.Hue = 2670;
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 2567 );
			ac.Light = LightType.ArchedWindowEast;
			ac.Hue = 2670;
			AddComponent( ac, 7, 5, 13 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 4, 7, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 3, 6, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 4, 6, 0 );
			ac = new AddonComponent( 10663 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 471 );
			ac.Hue = 2670;
			AddComponent( ac, 4, 6, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 3, 0 );
			ac = new AddonComponent( 473 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 4, 0 );
			ac = new AddonComponent( 470 );
			ac.Hue = 2670;
			AddComponent( ac, 3, 6, 0 );
			ac = new AddonComponent( 10667 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 472 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 3, 0 );
			ac = new AddonComponent( 10667 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 7, 4, 0 );
			ac = new AddonComponent( 465 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 5, 0 );
			ac = new AddonComponent( 465 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 464 );
			ac.Hue = 2670;
			AddComponent( ac, 5, 6, 0 );
			ac = new AddonComponent( 463 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 6, 0 );
			ac = new AddonComponent( 463 );
			ac.Hue = 2670;
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 7, 5, 0 );
			ac = new AddonComponent( 2208 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 5, 20 );
			ac = new AddonComponent( 2211 );
			ac.Hue = 2670;
			AddComponent( ac, 3, 4, 20 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 7, 7, 0 );
			ac = new AddonComponent( 10667 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2670;
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 7, 2, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 3, 7, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 7, 3, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 7, 1, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 5, 7, 0 );
			ac = new AddonComponent( 2567 );
			ac.Light = LightType.ArchedWindowEast;
			ac.Hue = 2670;
			AddComponent( ac, 7, 2, 13 );
			ac = new AddonComponent( 2572 );
			ac.Light = LightType.ArchedWindowEast;
			ac.Hue = 2670;
			AddComponent( ac, 5, 7, 13 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 7, 6, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 3, 5, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 7, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 4, 0 );
			ac = new AddonComponent( 2211 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 7, 5 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2670;
			AddComponent( ac, 6, 1, 0 );

		}

		public IllusionHouseTurqoiseAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class IllusionHouseTurqoiseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new IllusionHouseTurqoiseAddon();
			}
		}

		[Constructable]
		public IllusionHouseTurqoiseAddonDeed()
		{
			Name = "IllusionHouseTurqoise";
		}

		public IllusionHouseTurqoiseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}