
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KitchenIslandSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1848, -2, 0, 0}, {1848, -1, 0, 0}, {1848, 0, 0, 0}// 1	2	3	
			, {1848, 1, 0, 0}, {1848, -1, 1, 0}, {1848, 0, 1, 0}// 4	5	6	
			, {1848, 1, 1, 0}, {1848, -2, 0, 2}, {1848, -1, 0, 2}// 7	8	9	
			, {1848, 0, 0, 2}, {1848, 1, 0, 2}, {1293, -1, 1, 5}// 10	11	12	
			, {1293, 0, 1, 5}, {1293, 1, 1, 5}, {1293, -2, 0, 7}// 13	14	15	
			, {1293, -1, 0, 7}, {1293, 0, 0, 7}, {1293, 1, 0, 7}// 16	17	18	
			, {2602, -2, -1, 0}, {2602, -1, -1, 0}, {2602, 0, -1, 0}// 19	20	21	
			, {2602, 1, -1, 0}, {2883, -2, 1, 3}, {1848, -2, 1, 0}// 22	23	24	
			, {4100, -2, 1, 11}, {3577, -2, 1, 7}, {11599, -1, 1, 5}// 25	26	27	
			, {2450, 0, 1, 5}, {5638, 0, 1, 5}, {2494, -2, 0, 8}// 28	29	31	
			, {2494, -1, 0, 8}, {2494, 0, 0, 8}, {2494, 1, 0, 8}// 32	33	34	
			, {2479, -2, 0, 8}, {2479, -1, 0, 8}, {2479, 0, 0, 8}// 35	36	37	
			, {2479, 1, 0, 8}, {2495, -1, 1, 11}, {2495, 0, 1, 11}// 38	39	40	
			, {2495, 1, 1, 11}, {2495, 2, 1, 11}// 41	42	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KitchenIslandSouthAddonDeed();
			}
		}

		[ Constructable ]
		public KitchenIslandSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2430, 1, 1, 5, 0, -1, "", 2);// 30

		}

		public KitchenIslandSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KitchenIslandSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KitchenIslandSouthAddon();
			}
		}

		[Constructable]
		public KitchenIslandSouthAddonDeed()
		{
			Name = "KitchenIslandSouth";
		}

		public KitchenIslandSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}