
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class KitchenIslandEastSeatAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1848, -1, 0, 0}, {1848, -1, 1, 0}, {1848, -1, 2, 0}// 1	2	3	
			, {1848, 0, 0, 0}, {1848, 0, 1, 0}, {1848, 0, 2, 0}// 4	5	6	
			, {1848, 0, -1, 0}, {1848, 0, -1, 2}, {1848, 0, 0, 2}// 7	8	9	
			, {1848, 0, 1, 2}, {1848, 0, 2, 2}, {1294, 0, -1, 7}// 10	11	12	
			, {1294, 0, 0, 7}, {1294, 0, 1, 7}, {1294, 0, 2, 7}// 13	14	15	
			, {1294, -1, 0, 5}, {1294, -1, 1, 5}, {1294, -1, 2, 5}// 16	17	18	
			, {2602, 1, -1, 0}, {2602, 1, 0, 0}, {2602, 1, 1, 0}// 19	20	21	
			, {2602, 1, 2, 0}, {2883, -1, -1, 2}, {4100, -1, -1, 10}// 22	23	24	
			, {2520, 0, -1, 7}, {2520, 0, 0, 7}, {2520, 0, 1, 7}// 25	26	27	
			, {2520, 0, 2, 7}, {2517, 0, -1, 7}, {2517, 0, 0, 7}// 28	29	30	
			, {2517, 0, 1, 7}, {2517, 0, 2, 7}, {2495, 0, -1, 7}// 31	32	33	
			, {2495, 0, 0, 7}, {2495, 0, 1, 7}, {2495, 0, 2, 7}// 34	35	36	
			, {5638, -1, 0, 5}, {2449, -1, 2, 5}, {2539, -1, 2, 6}// 37	38	39	
			, {11599, -1, 1, 5}// 40	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new KitchenIslandEastSeatAddonDeed();
			}
		}

		[ Constructable ]
		public KitchenIslandEastSeatAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public KitchenIslandEastSeatAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class KitchenIslandEastSeatAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new KitchenIslandEastSeatAddon();
			}
		}

		[Constructable]
		public KitchenIslandEastSeatAddonDeed()
		{
			Name = "KitchenIslandEastSeat";
		}

		public KitchenIslandEastSeatAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}