/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MallasElfBannerEastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MallasElfBannerEastAddonDeed();
			}
		}

		[ Constructable ]
		public MallasElfBannerEastAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 5648 );
			ac.Hue = 2632;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 8708 );
			ac.Hue = 2632;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 8708 );
			ac.Hue = 2632;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 5647 );
			ac.Hue = 2632;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1 );
			ac.Hue = 2632;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 14678 );
			ac.Light = LightType.Circle225;
			ac.Hue = 2632;
			AddComponent( ac, 0, 0, 0 );

		}

		public MallasElfBannerEastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MallasElfBannerEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MallasElfBannerEastAddon();
			}
		}

		[Constructable]
		public MallasElfBannerEastAddonDeed()
		{
			Name = "MallasElfBannerEast";
		}

		public MallasElfBannerEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}