
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MLwoodenpathWEAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11576, -2, -1, 0}, {11576, -1, -1, 0}, {11576, 0, -1, 0}// 1	2	3	
			, {11576, 1, -1, 0}, {11576, 2, -1, 0}, {11576, 3, -1, 0}// 4	5	6	
			, {11726, -1, -2, 0}, {11726, 1, -2, 0}, {11726, 3, -2, 0}// 7	8	9	
			, {11725, -2, -2, 0}, {11725, 0, -2, 0}, {11725, 2, -2, 0}// 10	11	12	
			, {11724, -2, 2, 0}, {11724, 0, 2, 0}, {11724, 2, 2, 0}// 13	14	15	
			, {11723, -1, 2, 0}, {11723, 1, 2, 0}, {11723, 3, 2, 0}// 16	17	18	
			, {11576, -2, 0, 0}, {11576, -2, 1, 0}, {11576, -1, 0, 0}// 19	20	21	
			, {11576, -1, 1, 0}, {11576, 0, 0, 0}, {11576, 0, 1, 0}// 22	23	24	
			, {11576, 1, 0, 0}, {11576, 1, 1, 0}, {11576, 2, 0, 0}// 25	26	27	
			, {11576, 2, 1, 0}, {11576, 3, 0, 0}, {11576, 3, 1, 0}// 28	29	30	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MLwoodenpathWEAddonDeed();
			}
		}

		[ Constructable ]
		public MLwoodenpathWEAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public MLwoodenpathWEAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MLwoodenpathWEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MLwoodenpathWEAddon();
			}
		}

		[Constructable]
		public MLwoodenpathWEAddonDeed()
		{
			Name = "MLwoodenpathWE";
		}

		public MLwoodenpathWEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}