
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class PlanterVatAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {5342, -2, 0, 0}, {5335, 1, 1, 0}, {5338, 2, 0, 0}// 1	2	3	
			, {5339, -1, -1, 0}, {5343, 0, -2, 0}, {5341, 0, -1, 0}// 4	5	6	
			, {5340, -1, 0, 0}, {5337, 0, 0, 0}, {3265, 0, -1, 2}// 7	8	9	
			, {6013, -1, 0, 2}, {6013, -1, -1, 2}, {6013, 0, -1, 2}// 10	11	12	
			, {6013, 0, 0, 2}, {3265, 0, 0, 2}, {3265, -1, 1, 5}// 13	14	15	
			, {3265, -1, -1, 2}, {3265, 1, -1, 5}, {3265, -1, 0, 2}// 16	17	18	
			, {3232, 2, 0, 10}, {3232, 0, 1, 7}, {3236, 2, 1, 12}// 19	20	21	
			, {3149, -1, 0, 2}, {3149, 1, -1, 5}, {3149, 0, 0, 2}// 22	23	24	
			, {3149, -1, -1, 2}, {3204, 1, -1, 6}, {3204, -1, 1, 5}// 25	26	27	
			, {3263, 0, 0, 2}, {3263, 0, -1, 2}, {3263, -1, 0, 2}// 28	29	30	
			, {3263, -1, -1, 2}, {3214, 0, 0, 2}, {3214, 1, -1, 6}// 31	32	33	
			, {3214, -1, 1, 5}, {3214, -1, -1, 2}, {3302, -1, -1, 3}// 34	35	36	
			, {3303, -1, -1, 2}, {5336, 0, 2, 0}, {3236, 0, 2, 10}// 37	38	39	
			, {3314, 1, 2, 0}// 40	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new PlanterVatAddonDeed();
			}
		}

		[ Constructable ]
		public PlanterVatAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public PlanterVatAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class PlanterVatAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new PlanterVatAddon();
			}
		}

		[Constructable]
		public PlanterVatAddonDeed()
		{
			Name = "PlanterVat";
		}

		public PlanterVatAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}