
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class pulsingeggsackCDAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6077, 0, 0, 2}, {6085, -1, -1, 2}, {6086, 1, -1, 2}// 1	2	3	
			, {6087, 1, 1, 2}, {6088, -1, 1, 2}, {6089, 0, 1, 2}// 4	5	6	
			, {6090, -1, 0, 2}, {6091, 0, -1, 2}, {6092, 1, 0, 2}// 7	8	9	
			, {4312, -1, -1, 0}, {4313, 0, -1, 2}, {4317, 1, 1, 10}// 10	11	12	
			, {4311, 2, 0, 1}, {4310, 0, 2, 1}, {4313, 1, 0, 2}// 13	14	15	
			, {4313, 0, 1, 2}, {4313, -1, -1, 0}, {4313, -1, 0, 2}// 16	17	18	
			, {4313, 1, 1, 5}, {4314, 0, 0, 1}, {4313, -1, 1, 2}// 19	20	21	
			, {4313, -1, 0, 0}, {4313, 0, 1, 7}, {4313, 1, -1, 2}// 22	23	24	
			, {4313, 1, 0, 7}, {4313, 0, -1, 0}, {4312, 0, -1, 2}// 25	26	27	
			, {4312, -1, 0, 2}, {4312, -1, 1, 2}, {4312, 1, -1, 2}// 28	29	30	
			, {4312, 0, 1, 1}, {4312, 1, 0, 2}, {4311, -2, 0, 2}// 31	32	33	
			, {4310, 0, -2, 1}// 34	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new pulsingeggsackCDAddonDeed();
			}
		}

		[ Constructable ]
		public pulsingeggsackCDAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public pulsingeggsackCDAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class pulsingeggsackCDAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new pulsingeggsackCDAddon();
			}
		}

		[Constructable]
		public pulsingeggsackCDAddonDeed()
		{
			Name = "pulsingeggsackCD";
		}

		public pulsingeggsackCDAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}