
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class shipweAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6040, 5, 0, 7}, {6039, -4, 3, 7}, {6039, -4, 2, 7}// 1	 2	 3	 
			, {6039, -5, 2, 7}, {6043, -5, 3, 7}, {6043, -9, 4, 7}// 4	 5	 6	 
			, {6041, -7, 3, 7}, {6044, -7, 4, 7}, {6042, -10, 2, 7}// 7	 8	 9	 
			, {6043, 3, 4, 7}, {6040, 2, 4, 7}, {6040, 2, 3, 7}// 10	 11	 12	 
			, {6040, 2, 2, 7}, {6040, 0, 3, 7}, {6039, 0, 2, 7}// 13	 14	 15	 
			, {6039, -1, 2, 7}, {6042, -1, 3, 7}, {6050, 12, 3, 7}// 16	 17	 18	 
			, {6055, 10, 4, 7}, {6058, 10, 3, 7}, {6042, 10, 2, 7}// 19	 20	 21	 
			, {6044, 8, 3, 7}, {6040, 8, 2, 7}, {6039, 6, 3, 7}// 22	 23	 24	 
			, {6044, 6, 2, 7}, {6040, 6, 1, 7}, {6044, 6, 0, 7}// 25	 26	 27	 
			, {6041, 8, 1, 7}, {6044, 7, -1, 7}, {6039, 10, 1, 7}// 28	 29	 30	 
			, {6042, 10, 0, 7}, {6044, 10, -1, 7}, {6044, 10, -2, 7}// 31	 32	 33	 
			, {6042, -12, 3, 7}, {6039, -11, 3, 7}, {6042, -11, 4, 7}// 34	 35	 36	 
			, {6041, -12, 4, 7}, {6040, -3, 2, 7}, {6044, -3, 3, 7}// 37	 38	 39	 
			, {6043, -3, 4, 7}, {6044, -4, 4, 7}, {6040, -7, 2, 7}// 40	 41	 42	 
			, {6044, -10, 4, 7}, {6041, -10, 3, 7}, {6044, -8, 4, 7}// 43	 44	 45	 
			, {6043, -5, 4, 7}, {6044, -6, 4, 7}, {6043, -6, 3, 7}// 46	 47	 48	 
			, {6041, -6, 2, 7}, {6043, -8, 3, 7}, {6042, -8, 2, 7}// 49	 50	 51	 
			, {6044, -9, 2, 7}, {6042, -9, 3, 7}, {6040, 4, 3, 7}// 52	 53	 54	 
			, {6043, 4, 2, 7}, {6042, 3, 2, 7}, {6043, 3, 3, 7}// 55	 56	 57	 
			, {6043, 1, 2, 7}, {6039, 1, 3, 7}, {6043, 1, 4, 7}// 58	 59	 60	 
			, {6040, 0, 4, 7}, {6040, 9, 2, 7}, {6039, 9, 3, 7}// 61	 62	 63	 
			, {6050, 9, 4, 7}, {6050, 8, 4, 7}, {6040, 7, 0, 7}// 64	 65	 66	 
			, {6039, 9, -1, 7}, {6040, 9, 1, 7}, {6043, 12, -1, 7}// 67	 68	 69	 
			, {6041, 12, -2, 7}, {6040, 12, 1, 7}, {6042, 12, 0, 7}// 70	 71	 72	 
			, {6044, -2, 1, 7}, {6043, -1, 1, 7}, {6044, 0, 1, 7}// 73	 74	 75	 
			, {6044, 1, 1, 7}, {6042, 2, 1, 7}, {6039, 3, 1, 7}// 76	 77	 78	 
			, {6041, 4, 1, 7}, {6043, 5, 1, 7}, {6043, 5, 2, 7}// 79	 80	 81	 
			, {6041, 5, 3, 7}, {6044, 5, 4, 7}, {6040, 4, 4, 7}// 82	 83	 84	 
			, {6044, -1, 4, 7}, {6041, -2, 4, 7}, {6041, -2, 3, 7}// 85	 86	 87	 
			, {6039, -2, 2, 7}, {6042, 12, 2, 7}, {6040, 11, 2, 7}// 88	 89	 90	 
			, {6050, 11, 3, 7}, {6058, 7, 4, 7}, {6044, 6, 4, 7}// 91	 92	 93	 
			, {6043, 7, 2, 7}, {6042, 7, 3, 7}, {6039, 8, -1, 7}// 94	 95	 96	 
			, {6043, 7, 1, 7}, {6044, 9, 0, 7}, {6040, 8, 0, 7}// 97	 98	 99	 
			, {6039, 11, 0, 7}, {6042, 11, 1, 7}, {6043, 11, -2, 7}// 100	 101	 102	 
			, {6041, 11, -1, 7}, {499, 5, -2, 47}, {499, 5, -2, 62}// 103	 120	139	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new shipweAddonDeed();
			}
		}

		[ Constructable ]
		public shipweAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 16011, 2, 1, 8, 0, -1, "deck", 1);// 104
			AddComplexComponent( (BaseAddon) this, 16015, -3, 0, 8, 0, -1, "deck", 1);// 105
			AddComplexComponent( (BaseAddon) this, 16106, -1, -2, 8, 0, -1, "ship", 1);// 106
			AddComplexComponent( (BaseAddon) this, 15979, -2, 2, 11, 0, -1, "sail", 1);// 107
			AddComplexComponent( (BaseAddon) this, 16021, -5, 0, 8, 0, -1, "prow", 1);// 108
			AddComplexComponent( (BaseAddon) this, 15981, -2, -2, 0, 0, -1, "sail", 1);// 109
			AddComplexComponent( (BaseAddon) this, 16011, 5, -1, 8, 0, -1, "deck", 1);// 110
			AddComplexComponent( (BaseAddon) this, 16106, 2, -2, 8, 0, -1, "ship", 1);// 111
			AddComplexComponent( (BaseAddon) this, 16011, -1, -1, 8, 0, -1, "deck", 1);// 112
			AddComplexComponent( (BaseAddon) this, 16011, -2, 0, 8, 0, -1, "gangplank", 1);// 113
			AddComplexComponent( (BaseAddon) this, 16106, 3, -2, 8, 0, -1, "ship", 1);// 114
			AddComplexComponent( (BaseAddon) this, 8339, 5, -3, 65, 2615, -1, "Jolly Roger Flag", 1);// 115
			AddComplexComponent( (BaseAddon) this, 16106, 5, -2, 8, 0, -1, "ship", 1);// 116
			AddComplexComponent( (BaseAddon) this, 16012, -2, 1, 8, 0, -1, "ship", 1);// 117
			AddComplexComponent( (BaseAddon) this, 16000, 0, 1, 8, 0, -1, "ship", 1);// 118
			AddComplexComponent( (BaseAddon) this, 16105, 3, -1, 9, 0, -1, "ship", 1);// 119
			AddComplexComponent( (BaseAddon) this, 15978, 2, 3, 22, 0, -1, "sail", 1);// 121
			AddComplexComponent( (BaseAddon) this, 16011, 0, 0, 8, 0, -1, "deck", 1);// 122
			AddComplexComponent( (BaseAddon) this, 16011, 2, -1, 8, 0, -1, "deck", 1);// 123
			AddComplexComponent( (BaseAddon) this, 16011, 5, 0, 8, 0, -1, "deck", 1);// 124
			AddComplexComponent( (BaseAddon) this, 16106, 1, -2, 8, 0, -1, "ship", 1);// 125
			AddComplexComponent( (BaseAddon) this, 16105, -1, -1, 9, 0, -1, "ship", 1);// 126
			AddComplexComponent( (BaseAddon) this, 16013, -2, -1, 8, 0, -1, "deck", 1);// 127
			AddComplexComponent( (BaseAddon) this, 16016, -3, -1, 8, 0, -1, "deck", 1);// 128
			AddComplexComponent( (BaseAddon) this, 16011, 3, 0, 8, 0, -1, "deck", 1);// 129
			AddComplexComponent( (BaseAddon) this, 15980, -2, 0, 11, 0, -1, "ship", 1);// 130
			AddComplexComponent( (BaseAddon) this, 16011, 3, -1, 8, 0, -1, "deck", 1);// 131
			AddComplexComponent( (BaseAddon) this, 16011, 2, 0, 8, 0, -1, "gangplank", 1);// 132
			AddComplexComponent( (BaseAddon) this, 16105, 1, 2, 8, 0, -1, "ship", 1);// 133
			AddComplexComponent( (BaseAddon) this, 16001, 0, -1, 8, 0, -1, "ship", 1);// 134
			AddComplexComponent( (BaseAddon) this, 16017, -4, 1, 8, 0, -1, "ship", 1);// 135
			AddComplexComponent( (BaseAddon) this, 16105, 5, 2, 8, 0, -1, "ship", 1);// 136
			AddComplexComponent( (BaseAddon) this, 16105, 2, 2, 8, 0, -1, "ship", 1);// 137
			AddComplexComponent( (BaseAddon) this, 16105, 2, -1, 9, 0, -1, "ship", 1);// 138
			AddComplexComponent( (BaseAddon) this, 16011, 3, 1, 8, 0, -1, "deck", 1);// 140
			AddComplexComponent( (BaseAddon) this, 16011, 4, 0, 8, 0, -1, "deck", 1);// 141
			AddComplexComponent( (BaseAddon) this, 16105, 5, -1, 9, 0, -1, "ship", 1);// 142
			AddComplexComponent( (BaseAddon) this, 16011, -1, 1, 8, 0, -1, "deck", 1);// 143
			AddComplexComponent( (BaseAddon) this, 16000, 4, 1, 8, 0, -1, "ship", 1);// 144
			AddComplexComponent( (BaseAddon) this, 16105, -1, 2, 8, 0, -1, "ship", 1);// 145
			AddComplexComponent( (BaseAddon) this, 16001, 4, -1, 8, 0, -1, "ship", 1);// 146
			AddComplexComponent( (BaseAddon) this, 16011, -1, 0, 8, 0, -1, "deck", 1);// 147
			AddComplexComponent( (BaseAddon) this, 16011, 1, 1, 8, 0, -1, "deck", 1);// 148
			AddComplexComponent( (BaseAddon) this, 16019, -4, 0, 8, 0, -1, "deck", 1);// 149
			AddComplexComponent( (BaseAddon) this, 15979, 2, 2, 11, 0, -1, "sail", 1);// 150
			AddComplexComponent( (BaseAddon) this, 16011, 1, 0, 8, 0, -1, "cave floor", 1);// 151
			AddComplexComponent( (BaseAddon) this, 16105, 1, -1, 9, 0, -1, "ship", 1);// 152
			AddComplexComponent( (BaseAddon) this, 16011, 5, 1, 8, 0, -1, "deck", 1);// 153
			AddComplexComponent( (BaseAddon) this, 15978, -2, 3, 22, 0, -1, "sail", 1);// 154
			AddComplexComponent( (BaseAddon) this, 16014, -3, 1, 8, 0, -1, "ship", 1);// 155
			AddComplexComponent( (BaseAddon) this, 16011, 1, -1, 8, 0, -1, "deck", 1);// 156
			AddComplexComponent( (BaseAddon) this, 15980, 2, 0, 11, 0, -1, "mast", 1);// 157
			AddComplexComponent( (BaseAddon) this, 16020, -4, -1, 8, 0, -1, "ship", 1);// 158
			AddComplexComponent( (BaseAddon) this, 15981, 2, -2, 0, 0, -1, "sail", 1);// 159
			AddComplexComponent( (BaseAddon) this, 16011, 10, 0, 8, 0, -1, "deck", 1);// 160
			AddComplexComponent( (BaseAddon) this, 16011, 6, 1, 8, 0, -1, "deck", 1);// 161
			AddComplexComponent( (BaseAddon) this, 15998, 9, 1, 8, 0, -1, "ship", 1);// 162
			AddComplexComponent( (BaseAddon) this, 16105, 6, -1, 9, 0, -1, "ship", 1);// 163
			AddComplexComponent( (BaseAddon) this, 16108, 11, 0, 11, 0, -1, "ship", 1);// 164
			AddComplexComponent( (BaseAddon) this, 15979, 7, 2, 11, 0, -1, "sail", 1);// 165
			AddComplexComponent( (BaseAddon) this, 16106, 6, -2, 8, 0, -1, "ship", 1);// 166
			AddComplexComponent( (BaseAddon) this, 15978, 7, 3, 22, 0, -1, "sail", 1);// 167
			AddComplexComponent( (BaseAddon) this, 16011, 11, 0, 11, 0, -1, "deck", 1);// 168
			AddComplexComponent( (BaseAddon) this, 15981, 7, -2, 0, 0, -1, "sail", 1);// 169
			AddComplexComponent( (BaseAddon) this, 16106, 7, -2, 8, 0, -1, "ship", 1);// 170
			AddComplexComponent( (BaseAddon) this, 15995, 11, -1, 8, 0, -1, "ship", 1);// 171
			AddComplexComponent( (BaseAddon) this, 16105, 6, 2, 8, 0, -1, "ship", 1);// 172
			AddComplexComponent( (BaseAddon) this, 16011, 6, -1, 8, 0, -1, "deck", 1);// 173
			AddComplexComponent( (BaseAddon) this, 15999, 9, -1, 8, 0, -1, "ship", 1);// 174
			AddComplexComponent( (BaseAddon) this, 16011, 9, 0, 8, 0, -1, "deck", 1);// 175
			AddComplexComponent( (BaseAddon) this, 16011, 7, -1, 8, 0, -1, "deck", 1);// 176
			AddComplexComponent( (BaseAddon) this, 16011, 8, 0, 8, 0, -1, "deck", 1);// 177
			AddComplexComponent( (BaseAddon) this, 16001, 8, -1, 8, 0, -1, "ship", 1);// 178
			AddComplexComponent( (BaseAddon) this, 16011, 7, 1, 8, 0, -1, "deck", 1);// 179
			AddComplexComponent( (BaseAddon) this, 16011, 6, 0, 8, 0, -1, "gangplank", 1);// 180
			AddComplexComponent( (BaseAddon) this, 16105, 7, 2, 8, 0, -1, "ship", 1);// 181
			AddComplexComponent( (BaseAddon) this, 15980, 7, 0, 11, 0, -1, "mast", 1);// 182
			AddComplexComponent( (BaseAddon) this, 15996, 10, 1, 8, 0, -1, "ship", 1);// 183
			AddComplexComponent( (BaseAddon) this, 15993, 11, 1, 8, 0, -1, "ship", 1);// 184
			AddComplexComponent( (BaseAddon) this, 16105, 7, -1, 9, 0, -1, "ship", 1);// 185
			AddComplexComponent( (BaseAddon) this, 15997, 10, -1, 8, 0, -1, "ship", 1);// 186
			AddComplexComponent( (BaseAddon) this, 16011, 7, 0, 8, 0, -1, "deck", 1);// 187
			AddComplexComponent( (BaseAddon) this, 16000, 8, 1, 8, 0, -1, "ship", 1);// 188

		}

		public shipweAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class shipweAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new shipweAddon();
			}
		}

		[Constructable]
		public shipweAddonDeed()
		{
			Name = "shipwe";
		}

		public shipweAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}