
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SnowyGateEAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {9402, 0, -3, 0}, {9401, 0, -2, 0}, {9400, 0, -1, 0}// 1	2	3	
			, {9399, 0, 0, 0}, {9396, 0, 1, 0}, {9398, -2, 1, 0}// 4	5	6	
			, {3311, 1, -2, 0}, {3311, 1, -1, 0}, {3311, 0, -1, 0}// 7	8	9	
			, {3311, 1, 0, 0}, {3311, 1, 1, 0}, {7629, 1, 0, 0}// 10	11	12	
			, {7630, 1, -1, 0}, {9079, 1, -2, 0}, {9079, 1, 1, 0}// 13	14	15	
			, {6090, 1, 0, 45}, {6090, 1, 1, 45}, {6092, 2, 0, 45}// 16	17	18	
			, {6092, 2, 1, 45}, {6092, 2, 2, 45}, {6090, 1, 2, 45}// 19	20	21	
			, {6086, 2, -1, 45}, {6085, 1, -1, 45}, {6087, 2, 3, 45}// 22	23	24	
			, {6088, 1, 3, 45}, {6093, 2, 0, 0}, {6093, 2, -1, 0}// 25	26	27	
			, {6093, 2, -2, 0}, {6093, 2, 1, 0}, {6093, 1, -3, 0}// 28	29	30	
			, {6093, 1, 2, 0}, {6093, 2, -3, 0}, {6093, 2, 2, 0}// 31	32	33	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SnowyGateEAddonDeed();
			}
		}

		[ Constructable ]
		public SnowyGateEAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public SnowyGateEAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SnowyGateEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SnowyGateEAddon();
			}
		}

		[Constructable]
		public SnowyGateEAddonDeed()
		{
			Name = "SnowyGateE";
		}

		public SnowyGateEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}