/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class UnderTheSeaTilesAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new UnderTheSeaTilesAddonDeed();
			}
		}

		[ Constructable ]
		public UnderTheSeaTilesAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -3, -3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 1342 );
			ac.Hue = 99;
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 8131 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 13446 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 8109 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 8109 );
			AddComponent( ac, -2, -2, 0 );

		}

		public UnderTheSeaTilesAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class UnderTheSeaTilesAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new UnderTheSeaTilesAddon();
			}
		}

		[Constructable]
		public UnderTheSeaTilesAddonDeed()
		{
			Name = "UnderTheSeaTiles";
		}

		public UnderTheSeaTilesAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}