
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class YellowBrickRoadParkSquareAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new YellowBrickRoadParkSquareAddonDeed();
			}
		}

		[ Constructable ]
		public YellowBrickRoadParkSquareAddon()
		{



			AddComplexComponent( (BaseAddon) this, 1329, -18, -18, 0, 1260, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1329, -17, -18, 0, 1260, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1329, -16, -18, 0, 1260, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1329, -15, -18, 0, 1260, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1329, -14, -18, 0, 1260, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1329, -13, -18, 0, 1260, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1329, -12, -18, 0, 1260, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1329, -11, -18, 0, 1260, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1329, -10, -18, 0, 1260, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1329, -9, -18, 0, 1260, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1329, -8, -18, 0, 1260, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1329, -7, -18, 0, 1260, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1329, -6, -18, 0, 1260, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1329, -5, -18, 0, 1260, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1329, -4, -18, 0, 1260, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1329, -3, -18, 0, 1260, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1329, -18, -17, 0, 1260, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1329, -18, -16, 0, 1260, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1329, -18, -15, 0, 1260, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1329, -18, -14, 0, 1260, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1329, -18, -13, 0, 1260, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1329, -18, -12, 0, 1260, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1329, -18, -11, 0, 1260, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1329, -18, -10, 0, 1260, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 1329, -18, -9, 0, 1260, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 1329, -18, -8, 0, 1260, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 1329, -18, -7, 0, 1260, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1329, -18, -6, 0, 1260, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1329, -18, -5, 0, 1260, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1329, -18, -4, 0, 1260, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1329, -18, -3, 0, 1260, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1329, -18, -2, 0, 1260, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1329, -17, -17, 0, 1260, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1329, -17, -16, 0, 1260, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1329, -17, -15, 0, 1260, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1329, -17, -14, 0, 1260, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1329, -17, -13, 0, 1260, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1329, -17, -12, 0, 1260, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1329, -17, -11, 0, 1260, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1329, -17, -10, 0, 1260, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1329, -17, -9, 0, 1260, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1329, -17, -8, 0, 1260, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1329, -17, -7, 0, 1260, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1329, -17, -6, 0, 1260, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1329, -17, -5, 0, 1260, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 1329, -17, -4, 0, 1260, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1329, -17, -3, 0, 1260, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 1329, -17, -2, 0, 1260, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 1329, -16, -17, 0, 1260, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 1329, -16, -16, 0, 1260, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 1329, -16, -15, 0, 1260, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1329, -16, -14, 0, 1260, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1329, -16, -13, 0, 1260, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1329, -16, -12, 0, 1260, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1329, -16, -11, 0, 1260, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1329, -16, -10, 0, 1260, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1329, -16, -9, 0, 1260, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1329, -16, -8, 0, 1260, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1329, -16, -7, 0, 1260, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1329, -16, -6, 0, 1260, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1329, -16, -5, 0, 1260, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1329, -16, -4, 0, 1260, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1329, -16, -3, 0, 1260, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1329, -16, -2, 0, 1260, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1329, -15, -17, 0, 1260, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1329, -15, -16, 0, 1260, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1329, -15, -15, 0, 1260, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 1329, -15, -14, 0, 1260, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1329, -15, -13, 0, 1260, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1329, -15, -12, 0, 1260, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1329, -15, -11, 0, 1260, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1329, -15, -10, 0, 1260, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1329, -15, -9, 0, 1260, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1329, -15, -8, 0, 1260, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 1329, -15, -7, 0, 1260, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 1329, -15, -6, 0, 1260, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 1329, -15, -5, 0, 1260, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 1329, -15, -4, 0, 1260, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 1329, -15, -3, 0, 1260, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 1329, -15, -2, 0, 1260, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 1329, -14, -17, 0, 1260, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1329, -14, -16, 0, 1260, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1329, -14, -15, 0, 1260, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1329, -14, -14, 0, 1260, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1329, -14, -13, 0, 1260, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 1329, -14, -12, 0, 1260, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1329, -14, -11, 0, 1260, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1329, -14, -10, 0, 1260, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 1329, -14, -9, 0, 1260, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 1329, -14, -8, 0, 1260, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 1329, -14, -7, 0, 1260, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 1329, -14, -6, 0, 1260, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 1329, -14, -5, 0, 1260, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1329, -14, -4, 0, 1260, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1329, -14, -3, 0, 1260, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 1329, -14, -2, 0, 1260, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 1329, -13, -17, 0, 1260, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 1329, -13, -16, 0, 1260, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 1329, -13, -15, 0, 1260, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 1329, -13, -14, 0, 1260, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 1329, -12, -17, 0, 1260, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 1329, -12, -16, 0, 1260, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 1329, -12, -15, 0, 1260, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 1329, -12, -14, 0, 1260, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 1329, -11, -17, 0, 1260, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 1329, -11, -16, 0, 1260, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 1329, -11, -15, 0, 1260, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 1329, -11, -14, 0, 1260, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 1329, -10, -17, 0, 1260, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 1329, -10, -16, 0, 1260, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 1329, -10, -15, 0, 1260, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 1329, -10, -14, 0, 1260, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1329, -9, -17, 0, 1260, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 1329, -9, -16, 0, 1260, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 1329, -9, -15, 0, 1260, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 1329, -9, -14, 0, 1260, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 1329, -8, -17, 0, 1260, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 1329, -8, -16, 0, 1260, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1329, -8, -15, 0, 1260, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 1329, -8, -14, 0, 1260, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1329, -7, -17, 0, 1260, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1329, -7, -16, 0, 1260, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 1329, -7, -15, 0, 1260, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 1329, -7, -14, 0, 1260, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 1329, -6, -17, 0, 1260, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 1329, -6, -16, 0, 1260, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 1329, -6, -15, 0, 1260, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 1329, -6, -14, 0, 1260, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 1329, -5, -17, 0, 1260, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 1329, -5, -16, 0, 1260, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 1329, -5, -15, 0, 1260, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 1329, -5, -14, 0, 1260, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1329, -4, -17, 0, 1260, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 1329, -4, -16, 0, 1260, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 1329, -4, -15, 0, 1260, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 1329, -4, -14, 0, 1260, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 1329, -3, -17, 0, 1260, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 1329, -3, -16, 0, 1260, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 1329, -3, -15, 0, 1260, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 1329, -3, -14, 0, 1260, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 1329, -18, -1, 0, 1260, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1329, -18, 0, 0, 1260, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 1329, -18, 1, 0, 1260, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 1329, -18, 2, 0, 1260, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 1329, -18, 3, 0, 1260, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1329, -18, 4, 0, 1260, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 1329, -18, 5, 0, 1260, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1329, -18, 6, 0, 1260, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 1329, -18, 7, 0, 1260, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 1329, -18, 8, 0, 1260, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 1329, -18, 9, 0, 1260, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 1329, -18, 10, 0, 1260, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 1329, -18, 11, 0, 1260, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 1329, -18, 12, 0, 1260, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 1329, -18, 13, 0, 1260, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1329, -18, 14, 0, 1260, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 1329, -17, -1, 0, 1260, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1329, -17, 0, 0, 1260, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 1329, -17, 1, 0, 1260, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 1329, -17, 2, 0, 1260, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 1329, -17, 3, 0, 1260, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 1329, -17, 4, 0, 1260, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 1329, -17, 5, 0, 1260, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1329, -17, 6, 0, 1260, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1329, -17, 7, 0, 1260, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 1329, -17, 8, 0, 1260, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 1329, -17, 9, 0, 1260, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1329, -17, 10, 0, 1260, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 1329, -17, 11, 0, 1260, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 1329, -17, 12, 0, 1260, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 1329, -17, 13, 0, 1260, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 1329, -17, 14, 0, 1260, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1329, -16, -1, 0, 1260, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1329, -16, 0, 0, 1260, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1329, -16, 1, 0, 1260, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 1329, -16, 2, 0, 1260, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 1329, -16, 3, 0, 1260, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 1329, -16, 4, 0, 1260, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 1329, -16, 5, 0, 1260, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 1329, -16, 6, 0, 1260, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 1329, -16, 7, 0, 1260, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 1329, -16, 8, 0, 1260, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 1329, -16, 9, 0, 1260, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 1329, -16, 10, 0, 1260, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 1329, -16, 11, 0, 1260, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 1329, -16, 12, 0, 1260, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 1329, -16, 13, 0, 1260, -1, "", 1);// 187
			AddComplexComponent( (BaseAddon) this, 1329, -16, 14, 0, 1260, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 1329, -15, -1, 0, 1260, -1, "", 1);// 189
			AddComplexComponent( (BaseAddon) this, 1329, -15, 0, 0, 1260, -1, "", 1);// 190
			AddComplexComponent( (BaseAddon) this, 1329, -15, 1, 0, 1260, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 1329, -15, 2, 0, 1260, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 1329, -15, 3, 0, 1260, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 1329, -15, 4, 0, 1260, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 1329, -15, 5, 0, 1260, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 1329, -15, 6, 0, 1260, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 1329, -15, 7, 0, 1260, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 1329, -15, 8, 0, 1260, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 1329, -15, 9, 0, 1260, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 1329, -15, 10, 0, 1260, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 1329, -15, 11, 0, 1260, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 1329, -15, 12, 0, 1260, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 1329, -15, 13, 0, 1260, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 1329, -15, 14, 0, 1260, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 1329, -14, -1, 0, 1260, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 1329, -14, 0, 0, 1260, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 1329, -14, 1, 0, 1260, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 1329, -14, 2, 0, 1260, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 1329, -14, 3, 0, 1260, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 1329, -14, 4, 0, 1260, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 1329, -14, 5, 0, 1260, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 1329, -14, 6, 0, 1260, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 1329, -14, 7, 0, 1260, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 1329, -14, 8, 0, 1260, -1, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 1329, -14, 9, 0, 1260, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 1329, -14, 10, 0, 1260, -1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 1329, -14, 11, 0, 1260, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 1329, -14, 12, 0, 1260, -1, "", 1);// 218
			AddComplexComponent( (BaseAddon) this, 1329, -14, 13, 0, 1260, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 1329, -14, 14, 0, 1260, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 1329, -13, 14, 0, 1260, -1, "", 1);// 221
			AddComplexComponent( (BaseAddon) this, 1329, -12, 14, 0, 1260, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 1329, -11, 14, 0, 1260, -1, "", 1);// 223
			AddComplexComponent( (BaseAddon) this, 1329, -10, 14, 0, 1260, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 1329, -9, 14, 0, 1260, -1, "", 1);// 225
			AddComplexComponent( (BaseAddon) this, 1329, -8, 14, 0, 1260, -1, "", 1);// 226
			AddComplexComponent( (BaseAddon) this, 1329, -7, 14, 0, 1260, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 1329, -6, 14, 0, 1260, -1, "", 1);// 228
			AddComplexComponent( (BaseAddon) this, 1329, -5, 14, 0, 1260, -1, "", 1);// 229
			AddComplexComponent( (BaseAddon) this, 1329, -4, 14, 0, 1260, -1, "", 1);// 230
			AddComplexComponent( (BaseAddon) this, 1329, -3, 14, 0, 1260, -1, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 1329, -18, 15, 0, 1260, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 1329, -18, 16, 0, 1260, -1, "", 1);// 233
			AddComplexComponent( (BaseAddon) this, 1329, -18, 17, 0, 1260, -1, "", 1);// 234
			AddComplexComponent( (BaseAddon) this, 1329, -18, 18, 0, 1260, -1, "", 1);// 235
			AddComplexComponent( (BaseAddon) this, 1329, -17, 15, 0, 1260, -1, "", 1);// 236
			AddComplexComponent( (BaseAddon) this, 1329, -17, 16, 0, 1260, -1, "", 1);// 237
			AddComplexComponent( (BaseAddon) this, 1329, -17, 17, 0, 1260, -1, "", 1);// 238
			AddComplexComponent( (BaseAddon) this, 1329, -17, 18, 0, 1260, -1, "", 1);// 239
			AddComplexComponent( (BaseAddon) this, 1329, -16, 15, 0, 1260, -1, "", 1);// 240
			AddComplexComponent( (BaseAddon) this, 1329, -16, 16, 0, 1260, -1, "", 1);// 241
			AddComplexComponent( (BaseAddon) this, 1329, -16, 17, 0, 1260, -1, "", 1);// 242
			AddComplexComponent( (BaseAddon) this, 1329, -16, 18, 0, 1260, -1, "", 1);// 243
			AddComplexComponent( (BaseAddon) this, 1329, -15, 15, 0, 1260, -1, "", 1);// 244
			AddComplexComponent( (BaseAddon) this, 1329, -15, 16, 0, 1260, -1, "", 1);// 245
			AddComplexComponent( (BaseAddon) this, 1329, -15, 17, 0, 1260, -1, "", 1);// 246
			AddComplexComponent( (BaseAddon) this, 1329, -15, 18, 0, 1260, -1, "", 1);// 247
			AddComplexComponent( (BaseAddon) this, 1329, -14, 15, 0, 1260, -1, "", 1);// 248
			AddComplexComponent( (BaseAddon) this, 1329, -14, 16, 0, 1260, -1, "", 1);// 249
			AddComplexComponent( (BaseAddon) this, 1329, -14, 17, 0, 1260, -1, "", 1);// 250
			AddComplexComponent( (BaseAddon) this, 1329, -14, 18, 0, 1260, -1, "", 1);// 251
			AddComplexComponent( (BaseAddon) this, 1329, -13, 15, 0, 1260, -1, "", 1);// 252
			AddComplexComponent( (BaseAddon) this, 1329, -13, 16, 0, 1260, -1, "", 1);// 253
			AddComplexComponent( (BaseAddon) this, 1329, -13, 17, 0, 1260, -1, "", 1);// 254
			AddComplexComponent( (BaseAddon) this, 1329, -13, 18, 0, 1260, -1, "", 1);// 255
			AddComplexComponent( (BaseAddon) this, 1329, -12, 15, 0, 1260, -1, "", 1);// 256
			AddComplexComponent( (BaseAddon) this, 1329, -12, 16, 0, 1260, -1, "", 1);// 257
			AddComplexComponent( (BaseAddon) this, 1329, -12, 17, 0, 1260, -1, "", 1);// 258
			AddComplexComponent( (BaseAddon) this, 1329, -12, 18, 0, 1260, -1, "", 1);// 259
			AddComplexComponent( (BaseAddon) this, 1329, -11, 15, 0, 1260, -1, "", 1);// 260
			AddComplexComponent( (BaseAddon) this, 1329, -11, 16, 0, 1260, -1, "", 1);// 261
			AddComplexComponent( (BaseAddon) this, 1329, -11, 17, 0, 1260, -1, "", 1);// 262
			AddComplexComponent( (BaseAddon) this, 1329, -11, 18, 0, 1260, -1, "", 1);// 263
			AddComplexComponent( (BaseAddon) this, 1329, -10, 15, 0, 1260, -1, "", 1);// 264
			AddComplexComponent( (BaseAddon) this, 1329, -10, 16, 0, 1260, -1, "", 1);// 265
			AddComplexComponent( (BaseAddon) this, 1329, -10, 17, 0, 1260, -1, "", 1);// 266
			AddComplexComponent( (BaseAddon) this, 1329, -10, 18, 0, 1260, -1, "", 1);// 267
			AddComplexComponent( (BaseAddon) this, 1329, -9, 15, 0, 1260, -1, "", 1);// 268
			AddComplexComponent( (BaseAddon) this, 1329, -9, 16, 0, 1260, -1, "", 1);// 269
			AddComplexComponent( (BaseAddon) this, 1329, -9, 17, 0, 1260, -1, "", 1);// 270
			AddComplexComponent( (BaseAddon) this, 1329, -9, 18, 0, 1260, -1, "", 1);// 271
			AddComplexComponent( (BaseAddon) this, 1329, -8, 15, 0, 1260, -1, "", 1);// 272
			AddComplexComponent( (BaseAddon) this, 1329, -8, 16, 0, 1260, -1, "", 1);// 273
			AddComplexComponent( (BaseAddon) this, 1329, -8, 17, 0, 1260, -1, "", 1);// 274
			AddComplexComponent( (BaseAddon) this, 1329, -8, 18, 0, 1260, -1, "", 1);// 275
			AddComplexComponent( (BaseAddon) this, 1329, -7, 15, 0, 1260, -1, "", 1);// 276
			AddComplexComponent( (BaseAddon) this, 1329, -7, 16, 0, 1260, -1, "", 1);// 277
			AddComplexComponent( (BaseAddon) this, 1329, -7, 17, 0, 1260, -1, "", 1);// 278
			AddComplexComponent( (BaseAddon) this, 1329, -7, 18, 0, 1260, -1, "", 1);// 279
			AddComplexComponent( (BaseAddon) this, 1329, -6, 15, 0, 1260, -1, "", 1);// 280
			AddComplexComponent( (BaseAddon) this, 1329, -6, 16, 0, 1260, -1, "", 1);// 281
			AddComplexComponent( (BaseAddon) this, 1329, -6, 17, 0, 1260, -1, "", 1);// 282
			AddComplexComponent( (BaseAddon) this, 1329, -6, 18, 0, 1260, -1, "", 1);// 283
			AddComplexComponent( (BaseAddon) this, 1329, -5, 15, 0, 1260, -1, "", 1);// 284
			AddComplexComponent( (BaseAddon) this, 1329, -5, 16, 0, 1260, -1, "", 1);// 285
			AddComplexComponent( (BaseAddon) this, 1329, -5, 17, 0, 1260, -1, "", 1);// 286
			AddComplexComponent( (BaseAddon) this, 1329, -5, 18, 0, 1260, -1, "", 1);// 287
			AddComplexComponent( (BaseAddon) this, 1329, -4, 15, 0, 1260, -1, "", 1);// 288
			AddComplexComponent( (BaseAddon) this, 1329, -4, 16, 0, 1260, -1, "", 1);// 289
			AddComplexComponent( (BaseAddon) this, 1329, -4, 17, 0, 1260, -1, "", 1);// 290
			AddComplexComponent( (BaseAddon) this, 1329, -4, 18, 0, 1260, -1, "", 1);// 291
			AddComplexComponent( (BaseAddon) this, 1329, -3, 15, 0, 1260, -1, "", 1);// 292
			AddComplexComponent( (BaseAddon) this, 1329, -3, 16, 0, 1260, -1, "", 1);// 293
			AddComplexComponent( (BaseAddon) this, 1329, -3, 17, 0, 1260, -1, "", 1);// 294
			AddComplexComponent( (BaseAddon) this, 1329, -3, 18, 0, 1260, -1, "", 1);// 295
			AddComplexComponent( (BaseAddon) this, 1329, -2, -18, 0, 1260, -1, "", 1);// 296
			AddComplexComponent( (BaseAddon) this, 1329, -1, -18, 0, 1260, -1, "", 1);// 297
			AddComplexComponent( (BaseAddon) this, 1329, 0, -18, 0, 1260, -1, "", 1);// 298
			AddComplexComponent( (BaseAddon) this, 1329, 1, -18, 0, 1260, -1, "", 1);// 299
			AddComplexComponent( (BaseAddon) this, 1329, 2, -18, 0, 1260, -1, "", 1);// 300
			AddComplexComponent( (BaseAddon) this, 1329, 3, -18, 0, 1260, -1, "", 1);// 301
			AddComplexComponent( (BaseAddon) this, 1329, 4, -18, 0, 1260, -1, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 1329, 5, -18, 0, 1260, -1, "", 1);// 303
			AddComplexComponent( (BaseAddon) this, 1329, 6, -18, 0, 1260, -1, "", 1);// 304
			AddComplexComponent( (BaseAddon) this, 1329, 7, -18, 0, 1260, -1, "", 1);// 305
			AddComplexComponent( (BaseAddon) this, 1329, 8, -18, 0, 1260, -1, "", 1);// 306
			AddComplexComponent( (BaseAddon) this, 1329, 9, -18, 0, 1260, -1, "", 1);// 307
			AddComplexComponent( (BaseAddon) this, 1329, 10, -18, 0, 1260, -1, "", 1);// 308
			AddComplexComponent( (BaseAddon) this, 1329, 11, -18, 0, 1260, -1, "", 1);// 309
			AddComplexComponent( (BaseAddon) this, 1329, 12, -18, 0, 1260, -1, "", 1);// 310
			AddComplexComponent( (BaseAddon) this, 1329, 13, -18, 0, 1260, -1, "", 1);// 311
			AddComplexComponent( (BaseAddon) this, 1329, -2, -17, 0, 1260, -1, "", 1);// 312
			AddComplexComponent( (BaseAddon) this, 1329, -2, -16, 0, 1260, -1, "", 1);// 313
			AddComplexComponent( (BaseAddon) this, 1329, -2, -15, 0, 1260, -1, "", 1);// 314
			AddComplexComponent( (BaseAddon) this, 1329, -2, -14, 0, 1260, -1, "", 1);// 315
			AddComplexComponent( (BaseAddon) this, 1329, -1, -17, 0, 1260, -1, "", 1);// 316
			AddComplexComponent( (BaseAddon) this, 1329, -1, -16, 0, 1260, -1, "", 1);// 317
			AddComplexComponent( (BaseAddon) this, 1329, -1, -15, 0, 1260, -1, "", 1);// 318
			AddComplexComponent( (BaseAddon) this, 1329, -1, -14, 0, 1260, -1, "", 1);// 319
			AddComplexComponent( (BaseAddon) this, 1329, 0, -17, 0, 1260, -1, "", 1);// 320
			AddComplexComponent( (BaseAddon) this, 1329, 0, -16, 0, 1260, -1, "", 1);// 321
			AddComplexComponent( (BaseAddon) this, 1329, 0, -15, 0, 1260, -1, "", 1);// 322
			AddComplexComponent( (BaseAddon) this, 1329, 0, -14, 0, 1260, -1, "", 1);// 323
			AddComplexComponent( (BaseAddon) this, 1329, 1, -17, 0, 1260, -1, "", 1);// 324
			AddComplexComponent( (BaseAddon) this, 1329, 1, -16, 0, 1260, -1, "", 1);// 325
			AddComplexComponent( (BaseAddon) this, 1329, 1, -15, 0, 1260, -1, "", 1);// 326
			AddComplexComponent( (BaseAddon) this, 1329, 1, -14, 0, 1260, -1, "", 1);// 327
			AddComplexComponent( (BaseAddon) this, 1329, 2, -17, 0, 1260, -1, "", 1);// 328
			AddComplexComponent( (BaseAddon) this, 1329, 2, -16, 0, 1260, -1, "", 1);// 329
			AddComplexComponent( (BaseAddon) this, 1329, 2, -15, 0, 1260, -1, "", 1);// 330
			AddComplexComponent( (BaseAddon) this, 1329, 2, -14, 0, 1260, -1, "", 1);// 331
			AddComplexComponent( (BaseAddon) this, 1329, 3, -17, 0, 1260, -1, "", 1);// 332
			AddComplexComponent( (BaseAddon) this, 1329, 3, -16, 0, 1260, -1, "", 1);// 333
			AddComplexComponent( (BaseAddon) this, 1329, 3, -15, 0, 1260, -1, "", 1);// 334
			AddComplexComponent( (BaseAddon) this, 1329, 3, -14, 0, 1260, -1, "", 1);// 335
			AddComplexComponent( (BaseAddon) this, 1329, 4, -17, 0, 1260, -1, "", 1);// 336
			AddComplexComponent( (BaseAddon) this, 1329, 4, -16, 0, 1260, -1, "", 1);// 337
			AddComplexComponent( (BaseAddon) this, 1329, 4, -15, 0, 1260, -1, "", 1);// 338
			AddComplexComponent( (BaseAddon) this, 1329, 4, -14, 0, 1260, -1, "", 1);// 339
			AddComplexComponent( (BaseAddon) this, 1329, 5, -17, 0, 1260, -1, "", 1);// 340
			AddComplexComponent( (BaseAddon) this, 1329, 5, -16, 0, 1260, -1, "", 1);// 341
			AddComplexComponent( (BaseAddon) this, 1329, 5, -15, 0, 1260, -1, "", 1);// 342
			AddComplexComponent( (BaseAddon) this, 1329, 5, -14, 0, 1260, -1, "", 1);// 343
			AddComplexComponent( (BaseAddon) this, 1329, 6, -17, 0, 1260, -1, "", 1);// 344
			AddComplexComponent( (BaseAddon) this, 1329, 6, -16, 0, 1260, -1, "", 1);// 345
			AddComplexComponent( (BaseAddon) this, 1329, 6, -15, 0, 1260, -1, "", 1);// 346
			AddComplexComponent( (BaseAddon) this, 1329, 6, -14, 0, 1260, -1, "", 1);// 347
			AddComplexComponent( (BaseAddon) this, 1329, 7, -17, 0, 1260, -1, "", 1);// 348
			AddComplexComponent( (BaseAddon) this, 1329, 7, -16, 0, 1260, -1, "", 1);// 349
			AddComplexComponent( (BaseAddon) this, 1329, 7, -15, 0, 1260, -1, "", 1);// 350
			AddComplexComponent( (BaseAddon) this, 1329, 7, -14, 0, 1260, -1, "", 1);// 351
			AddComplexComponent( (BaseAddon) this, 1329, 8, -17, 0, 1260, -1, "", 1);// 352
			AddComplexComponent( (BaseAddon) this, 1329, 8, -16, 0, 1260, -1, "", 1);// 353
			AddComplexComponent( (BaseAddon) this, 1329, 8, -15, 0, 1260, -1, "", 1);// 354
			AddComplexComponent( (BaseAddon) this, 1329, 8, -14, 0, 1260, -1, "", 1);// 355
			AddComplexComponent( (BaseAddon) this, 1329, 9, -17, 0, 1260, -1, "", 1);// 356
			AddComplexComponent( (BaseAddon) this, 1329, 9, -16, 0, 1260, -1, "", 1);// 357
			AddComplexComponent( (BaseAddon) this, 1329, 9, -15, 0, 1260, -1, "", 1);// 358
			AddComplexComponent( (BaseAddon) this, 1329, 9, -14, 0, 1260, -1, "", 1);// 359
			AddComplexComponent( (BaseAddon) this, 1329, 10, -17, 0, 1260, -1, "", 1);// 360
			AddComplexComponent( (BaseAddon) this, 1329, 10, -16, 0, 1260, -1, "", 1);// 361
			AddComplexComponent( (BaseAddon) this, 1329, 10, -15, 0, 1260, -1, "", 1);// 362
			AddComplexComponent( (BaseAddon) this, 1329, 10, -14, 0, 1260, -1, "", 1);// 363
			AddComplexComponent( (BaseAddon) this, 1329, 11, -17, 0, 1260, -1, "", 1);// 364
			AddComplexComponent( (BaseAddon) this, 1329, 11, -16, 0, 1260, -1, "", 1);// 365
			AddComplexComponent( (BaseAddon) this, 1329, 11, -15, 0, 1260, -1, "", 1);// 366
			AddComplexComponent( (BaseAddon) this, 1329, 11, -14, 0, 1260, -1, "", 1);// 367
			AddComplexComponent( (BaseAddon) this, 1329, 12, -17, 0, 1260, -1, "", 1);// 368
			AddComplexComponent( (BaseAddon) this, 1329, 12, -16, 0, 1260, -1, "", 1);// 369
			AddComplexComponent( (BaseAddon) this, 1329, 12, -15, 0, 1260, -1, "", 1);// 370
			AddComplexComponent( (BaseAddon) this, 1329, 12, -14, 0, 1260, -1, "", 1);// 371
			AddComplexComponent( (BaseAddon) this, 1329, 13, -17, 0, 1260, -1, "", 1);// 372
			AddComplexComponent( (BaseAddon) this, 1329, 13, -16, 0, 1260, -1, "", 1);// 373
			AddComplexComponent( (BaseAddon) this, 1329, 13, -15, 0, 1260, -1, "", 1);// 374
			AddComplexComponent( (BaseAddon) this, 1329, 13, -14, 0, 1260, -1, "", 1);// 375
			AddComplexComponent( (BaseAddon) this, 1329, -2, 14, 0, 1260, -1, "", 1);// 376
			AddComplexComponent( (BaseAddon) this, 1329, -1, 14, 0, 1260, -1, "", 1);// 377
			AddComplexComponent( (BaseAddon) this, 1329, 0, 14, 0, 1260, -1, "", 1);// 378
			AddComplexComponent( (BaseAddon) this, 1329, 1, 14, 0, 1260, -1, "", 1);// 379
			AddComplexComponent( (BaseAddon) this, 1329, 2, 14, 0, 1260, -1, "", 1);// 380
			AddComplexComponent( (BaseAddon) this, 1329, 3, 14, 0, 1260, -1, "", 1);// 381
			AddComplexComponent( (BaseAddon) this, 1329, 4, 14, 0, 1260, -1, "", 1);// 382
			AddComplexComponent( (BaseAddon) this, 1329, 5, 14, 0, 1260, -1, "", 1);// 383
			AddComplexComponent( (BaseAddon) this, 1329, 6, 14, 0, 1260, -1, "", 1);// 384
			AddComplexComponent( (BaseAddon) this, 1329, 7, 14, 0, 1260, -1, "", 1);// 385
			AddComplexComponent( (BaseAddon) this, 1329, 8, 14, 0, 1260, -1, "", 1);// 386
			AddComplexComponent( (BaseAddon) this, 1329, 9, 14, 0, 1260, -1, "", 1);// 387
			AddComplexComponent( (BaseAddon) this, 1329, 10, 14, 0, 1260, -1, "", 1);// 388
			AddComplexComponent( (BaseAddon) this, 1329, 11, 14, 0, 1260, -1, "", 1);// 389
			AddComplexComponent( (BaseAddon) this, 1329, 12, 14, 0, 1260, -1, "", 1);// 390
			AddComplexComponent( (BaseAddon) this, 1329, 13, 14, 0, 1260, -1, "", 1);// 391
			AddComplexComponent( (BaseAddon) this, 1329, -2, 15, 0, 1260, -1, "", 1);// 392
			AddComplexComponent( (BaseAddon) this, 1329, -2, 16, 0, 1260, -1, "", 1);// 393
			AddComplexComponent( (BaseAddon) this, 1329, -2, 17, 0, 1260, -1, "", 1);// 394
			AddComplexComponent( (BaseAddon) this, 1329, -2, 18, 0, 1260, -1, "", 1);// 395
			AddComplexComponent( (BaseAddon) this, 1329, -1, 15, 0, 1260, -1, "", 1);// 396
			AddComplexComponent( (BaseAddon) this, 1329, -1, 16, 0, 1260, -1, "", 1);// 397
			AddComplexComponent( (BaseAddon) this, 1329, -1, 17, 0, 1260, -1, "", 1);// 398
			AddComplexComponent( (BaseAddon) this, 1329, -1, 18, 0, 1260, -1, "", 1);// 399
			AddComplexComponent( (BaseAddon) this, 1329, 0, 15, 0, 1260, -1, "", 1);// 400
			AddComplexComponent( (BaseAddon) this, 1329, 0, 16, 0, 1260, -1, "", 1);// 401
			AddComplexComponent( (BaseAddon) this, 1329, 0, 17, 0, 1260, -1, "", 1);// 402
			AddComplexComponent( (BaseAddon) this, 1329, 0, 18, 0, 1260, -1, "", 1);// 403
			AddComplexComponent( (BaseAddon) this, 1329, 1, 15, 0, 1260, -1, "", 1);// 404
			AddComplexComponent( (BaseAddon) this, 1329, 1, 16, 0, 1260, -1, "", 1);// 405
			AddComplexComponent( (BaseAddon) this, 1329, 1, 17, 0, 1260, -1, "", 1);// 406
			AddComplexComponent( (BaseAddon) this, 1329, 1, 18, 0, 1260, -1, "", 1);// 407
			AddComplexComponent( (BaseAddon) this, 1329, 2, 15, 0, 1260, -1, "", 1);// 408
			AddComplexComponent( (BaseAddon) this, 1329, 2, 16, 0, 1260, -1, "", 1);// 409
			AddComplexComponent( (BaseAddon) this, 1329, 2, 17, 0, 1260, -1, "", 1);// 410
			AddComplexComponent( (BaseAddon) this, 1329, 2, 18, 0, 1260, -1, "", 1);// 411
			AddComplexComponent( (BaseAddon) this, 1329, 3, 15, 0, 1260, -1, "", 1);// 412
			AddComplexComponent( (BaseAddon) this, 1329, 3, 16, 0, 1260, -1, "", 1);// 413
			AddComplexComponent( (BaseAddon) this, 1329, 3, 17, 0, 1260, -1, "", 1);// 414
			AddComplexComponent( (BaseAddon) this, 1329, 3, 18, 0, 1260, -1, "", 1);// 415
			AddComplexComponent( (BaseAddon) this, 1329, 4, 15, 0, 1260, -1, "", 1);// 416
			AddComplexComponent( (BaseAddon) this, 1329, 4, 16, 0, 1260, -1, "", 1);// 417
			AddComplexComponent( (BaseAddon) this, 1329, 4, 17, 0, 1260, -1, "", 1);// 418
			AddComplexComponent( (BaseAddon) this, 1329, 4, 18, 0, 1260, -1, "", 1);// 419
			AddComplexComponent( (BaseAddon) this, 1329, 5, 15, 0, 1260, -1, "", 1);// 420
			AddComplexComponent( (BaseAddon) this, 1329, 5, 16, 0, 1260, -1, "", 1);// 421
			AddComplexComponent( (BaseAddon) this, 1329, 5, 17, 0, 1260, -1, "", 1);// 422
			AddComplexComponent( (BaseAddon) this, 1329, 5, 18, 0, 1260, -1, "", 1);// 423
			AddComplexComponent( (BaseAddon) this, 1329, 6, 15, 0, 1260, -1, "", 1);// 424
			AddComplexComponent( (BaseAddon) this, 1329, 6, 16, 0, 1260, -1, "", 1);// 425
			AddComplexComponent( (BaseAddon) this, 1329, 6, 17, 0, 1260, -1, "", 1);// 426
			AddComplexComponent( (BaseAddon) this, 1329, 6, 18, 0, 1260, -1, "", 1);// 427
			AddComplexComponent( (BaseAddon) this, 1329, 7, 15, 0, 1260, -1, "", 1);// 428
			AddComplexComponent( (BaseAddon) this, 1329, 7, 16, 0, 1260, -1, "", 1);// 429
			AddComplexComponent( (BaseAddon) this, 1329, 7, 17, 0, 1260, -1, "", 1);// 430
			AddComplexComponent( (BaseAddon) this, 1329, 7, 18, 0, 1260, -1, "", 1);// 431
			AddComplexComponent( (BaseAddon) this, 1329, 8, 15, 0, 1260, -1, "", 1);// 432
			AddComplexComponent( (BaseAddon) this, 1329, 8, 16, 0, 1260, -1, "", 1);// 433
			AddComplexComponent( (BaseAddon) this, 1329, 8, 17, 0, 1260, -1, "", 1);// 434
			AddComplexComponent( (BaseAddon) this, 1329, 8, 18, 0, 1260, -1, "", 1);// 435
			AddComplexComponent( (BaseAddon) this, 1329, 9, 15, 0, 1260, -1, "", 1);// 436
			AddComplexComponent( (BaseAddon) this, 1329, 9, 16, 0, 1260, -1, "", 1);// 437
			AddComplexComponent( (BaseAddon) this, 1329, 9, 17, 0, 1260, -1, "", 1);// 438
			AddComplexComponent( (BaseAddon) this, 1329, 9, 18, 0, 1260, -1, "", 1);// 439
			AddComplexComponent( (BaseAddon) this, 1329, 10, 15, 0, 1260, -1, "", 1);// 440
			AddComplexComponent( (BaseAddon) this, 1329, 10, 16, 0, 1260, -1, "", 1);// 441
			AddComplexComponent( (BaseAddon) this, 1329, 10, 17, 0, 1260, -1, "", 1);// 442
			AddComplexComponent( (BaseAddon) this, 1329, 10, 18, 0, 1260, -1, "", 1);// 443
			AddComplexComponent( (BaseAddon) this, 1329, 11, 15, 0, 1260, -1, "", 1);// 444
			AddComplexComponent( (BaseAddon) this, 1329, 11, 16, 0, 1260, -1, "", 1);// 445
			AddComplexComponent( (BaseAddon) this, 1329, 11, 17, 0, 1260, -1, "", 1);// 446
			AddComplexComponent( (BaseAddon) this, 1329, 11, 18, 0, 1260, -1, "", 1);// 447
			AddComplexComponent( (BaseAddon) this, 1329, 12, 15, 0, 1260, -1, "", 1);// 448
			AddComplexComponent( (BaseAddon) this, 1329, 12, 16, 0, 1260, -1, "", 1);// 449
			AddComplexComponent( (BaseAddon) this, 1329, 12, 17, 0, 1260, -1, "", 1);// 450
			AddComplexComponent( (BaseAddon) this, 1329, 12, 18, 0, 1260, -1, "", 1);// 451
			AddComplexComponent( (BaseAddon) this, 1329, 13, 15, 0, 1260, -1, "", 1);// 452
			AddComplexComponent( (BaseAddon) this, 1329, 13, 16, 0, 1260, -1, "", 1);// 453
			AddComplexComponent( (BaseAddon) this, 1329, 13, 17, 0, 1260, -1, "", 1);// 454
			AddComplexComponent( (BaseAddon) this, 1329, 13, 18, 0, 1260, -1, "", 1);// 455
			AddComplexComponent( (BaseAddon) this, 1329, 14, -18, 0, 1260, -1, "", 1);// 456
			AddComplexComponent( (BaseAddon) this, 1329, 15, -18, 0, 1260, -1, "", 1);// 457
			AddComplexComponent( (BaseAddon) this, 1329, 16, -18, 0, 1260, -1, "", 1);// 458
			AddComplexComponent( (BaseAddon) this, 1329, 17, -18, 0, 1260, -1, "", 1);// 459
			AddComplexComponent( (BaseAddon) this, 1329, 18, -18, 0, 1260, -1, "", 1);// 460
			AddComplexComponent( (BaseAddon) this, 1329, 14, -17, 0, 1260, -1, "", 1);// 461
			AddComplexComponent( (BaseAddon) this, 1329, 14, -16, 0, 1260, -1, "", 1);// 462
			AddComplexComponent( (BaseAddon) this, 1329, 14, -15, 0, 1260, -1, "", 1);// 463
			AddComplexComponent( (BaseAddon) this, 1329, 14, -14, 0, 1260, -1, "", 1);// 464
			AddComplexComponent( (BaseAddon) this, 1329, 14, -13, 0, 1260, -1, "", 1);// 465
			AddComplexComponent( (BaseAddon) this, 1329, 14, -12, 0, 1260, -1, "", 1);// 466
			AddComplexComponent( (BaseAddon) this, 1329, 14, -11, 0, 1260, -1, "", 1);// 467
			AddComplexComponent( (BaseAddon) this, 1329, 14, -10, 0, 1260, -1, "", 1);// 468
			AddComplexComponent( (BaseAddon) this, 1329, 14, -9, 0, 1260, -1, "", 1);// 469
			AddComplexComponent( (BaseAddon) this, 1329, 14, -8, 0, 1260, -1, "", 1);// 470
			AddComplexComponent( (BaseAddon) this, 1329, 14, -7, 0, 1260, -1, "", 1);// 471
			AddComplexComponent( (BaseAddon) this, 1329, 14, -6, 0, 1260, -1, "", 1);// 472
			AddComplexComponent( (BaseAddon) this, 1329, 14, -5, 0, 1260, -1, "", 1);// 473
			AddComplexComponent( (BaseAddon) this, 1329, 14, -4, 0, 1260, -1, "", 1);// 474
			AddComplexComponent( (BaseAddon) this, 1329, 14, -3, 0, 1260, -1, "", 1);// 475
			AddComplexComponent( (BaseAddon) this, 1329, 14, -2, 0, 1260, -1, "", 1);// 476
			AddComplexComponent( (BaseAddon) this, 1329, 15, -17, 0, 1260, -1, "", 1);// 477
			AddComplexComponent( (BaseAddon) this, 1329, 15, -16, 0, 1260, -1, "", 1);// 478
			AddComplexComponent( (BaseAddon) this, 1329, 15, -15, 0, 1260, -1, "", 1);// 479
			AddComplexComponent( (BaseAddon) this, 1329, 15, -14, 0, 1260, -1, "", 1);// 480
			AddComplexComponent( (BaseAddon) this, 1329, 15, -13, 0, 1260, -1, "", 1);// 481
			AddComplexComponent( (BaseAddon) this, 1329, 15, -12, 0, 1260, -1, "", 1);// 482
			AddComplexComponent( (BaseAddon) this, 1329, 15, -11, 0, 1260, -1, "", 1);// 483
			AddComplexComponent( (BaseAddon) this, 1329, 15, -10, 0, 1260, -1, "", 1);// 484
			AddComplexComponent( (BaseAddon) this, 1329, 15, -9, 0, 1260, -1, "", 1);// 485
			AddComplexComponent( (BaseAddon) this, 1329, 15, -8, 0, 1260, -1, "", 1);// 486
			AddComplexComponent( (BaseAddon) this, 1329, 15, -7, 0, 1260, -1, "", 1);// 487
			AddComplexComponent( (BaseAddon) this, 1329, 15, -6, 0, 1260, -1, "", 1);// 488
			AddComplexComponent( (BaseAddon) this, 1329, 15, -5, 0, 1260, -1, "", 1);// 489
			AddComplexComponent( (BaseAddon) this, 1329, 15, -4, 0, 1260, -1, "", 1);// 490
			AddComplexComponent( (BaseAddon) this, 1329, 15, -3, 0, 1260, -1, "", 1);// 491
			AddComplexComponent( (BaseAddon) this, 1329, 15, -2, 0, 1260, -1, "", 1);// 492
			AddComplexComponent( (BaseAddon) this, 1329, 16, -17, 0, 1260, -1, "", 1);// 493
			AddComplexComponent( (BaseAddon) this, 1329, 16, -16, 0, 1260, -1, "", 1);// 494
			AddComplexComponent( (BaseAddon) this, 1329, 16, -15, 0, 1260, -1, "", 1);// 495
			AddComplexComponent( (BaseAddon) this, 1329, 16, -14, 0, 1260, -1, "", 1);// 496
			AddComplexComponent( (BaseAddon) this, 1329, 16, -13, 0, 1260, -1, "", 1);// 497
			AddComplexComponent( (BaseAddon) this, 1329, 16, -12, 0, 1260, -1, "", 1);// 498
			AddComplexComponent( (BaseAddon) this, 1329, 16, -11, 0, 1260, -1, "", 1);// 499
			AddComplexComponent( (BaseAddon) this, 1329, 16, -10, 0, 1260, -1, "", 1);// 500
			AddComplexComponent( (BaseAddon) this, 1329, 16, -9, 0, 1260, -1, "", 1);// 501
			AddComplexComponent( (BaseAddon) this, 1329, 16, -8, 0, 1260, -1, "", 1);// 502
			AddComplexComponent( (BaseAddon) this, 1329, 16, -7, 0, 1260, -1, "", 1);// 503
			AddComplexComponent( (BaseAddon) this, 1329, 16, -6, 0, 1260, -1, "", 1);// 504
			AddComplexComponent( (BaseAddon) this, 1329, 16, -5, 0, 1260, -1, "", 1);// 505
			AddComplexComponent( (BaseAddon) this, 1329, 16, -4, 0, 1260, -1, "", 1);// 506
			AddComplexComponent( (BaseAddon) this, 1329, 16, -3, 0, 1260, -1, "", 1);// 507
			AddComplexComponent( (BaseAddon) this, 1329, 16, -2, 0, 1260, -1, "", 1);// 508
			AddComplexComponent( (BaseAddon) this, 1329, 17, -17, 0, 1260, -1, "", 1);// 509
			AddComplexComponent( (BaseAddon) this, 1329, 17, -16, 0, 1260, -1, "", 1);// 510
			AddComplexComponent( (BaseAddon) this, 1329, 17, -15, 0, 1260, -1, "", 1);// 511
			AddComplexComponent( (BaseAddon) this, 1329, 17, -14, 0, 1260, -1, "", 1);// 512
			AddComplexComponent( (BaseAddon) this, 1329, 17, -13, 0, 1260, -1, "", 1);// 513
			AddComplexComponent( (BaseAddon) this, 1329, 17, -12, 0, 1260, -1, "", 1);// 514
			AddComplexComponent( (BaseAddon) this, 1329, 17, -11, 0, 1260, -1, "", 1);// 515
			AddComplexComponent( (BaseAddon) this, 1329, 17, -10, 0, 1260, -1, "", 1);// 516
			AddComplexComponent( (BaseAddon) this, 1329, 17, -9, 0, 1260, -1, "", 1);// 517
			AddComplexComponent( (BaseAddon) this, 1329, 17, -8, 0, 1260, -1, "", 1);// 518
			AddComplexComponent( (BaseAddon) this, 1329, 17, -7, 0, 1260, -1, "", 1);// 519
			AddComplexComponent( (BaseAddon) this, 1329, 17, -6, 0, 1260, -1, "", 1);// 520
			AddComplexComponent( (BaseAddon) this, 1329, 17, -5, 0, 1260, -1, "", 1);// 521
			AddComplexComponent( (BaseAddon) this, 1329, 17, -4, 0, 1260, -1, "", 1);// 522
			AddComplexComponent( (BaseAddon) this, 1329, 17, -3, 0, 1260, -1, "", 1);// 523
			AddComplexComponent( (BaseAddon) this, 1329, 17, -2, 0, 1260, -1, "", 1);// 524
			AddComplexComponent( (BaseAddon) this, 1329, 18, -17, 0, 1260, -1, "", 1);// 525
			AddComplexComponent( (BaseAddon) this, 1329, 18, -16, 0, 1260, -1, "", 1);// 526
			AddComplexComponent( (BaseAddon) this, 1329, 18, -15, 0, 1260, -1, "", 1);// 527
			AddComplexComponent( (BaseAddon) this, 1329, 18, -14, 0, 1260, -1, "", 1);// 528
			AddComplexComponent( (BaseAddon) this, 1329, 18, -13, 0, 1260, -1, "", 1);// 529
			AddComplexComponent( (BaseAddon) this, 1329, 18, -12, 0, 1260, -1, "", 1);// 530
			AddComplexComponent( (BaseAddon) this, 1329, 18, -11, 0, 1260, -1, "", 1);// 531
			AddComplexComponent( (BaseAddon) this, 1329, 18, -10, 0, 1260, -1, "", 1);// 532
			AddComplexComponent( (BaseAddon) this, 1329, 18, -9, 0, 1260, -1, "", 1);// 533
			AddComplexComponent( (BaseAddon) this, 1329, 18, -8, 0, 1260, -1, "", 1);// 534
			AddComplexComponent( (BaseAddon) this, 1329, 18, -7, 0, 1260, -1, "", 1);// 535
			AddComplexComponent( (BaseAddon) this, 1329, 18, -6, 0, 1260, -1, "", 1);// 536
			AddComplexComponent( (BaseAddon) this, 1329, 18, -5, 0, 1260, -1, "", 1);// 537
			AddComplexComponent( (BaseAddon) this, 1329, 18, -4, 0, 1260, -1, "", 1);// 538
			AddComplexComponent( (BaseAddon) this, 1329, 18, -3, 0, 1260, -1, "", 1);// 539
			AddComplexComponent( (BaseAddon) this, 1329, 18, -2, 0, 1260, -1, "", 1);// 540
			AddComplexComponent( (BaseAddon) this, 1329, 14, -1, 0, 1260, -1, "", 1);// 541
			AddComplexComponent( (BaseAddon) this, 1329, 14, 0, 0, 1260, -1, "", 1);// 542
			AddComplexComponent( (BaseAddon) this, 1329, 14, 1, 0, 1260, -1, "", 1);// 543
			AddComplexComponent( (BaseAddon) this, 1329, 14, 2, 0, 1260, -1, "", 1);// 544
			AddComplexComponent( (BaseAddon) this, 1329, 14, 3, 0, 1260, -1, "", 1);// 545
			AddComplexComponent( (BaseAddon) this, 1329, 14, 4, 0, 1260, -1, "", 1);// 546
			AddComplexComponent( (BaseAddon) this, 1329, 14, 5, 0, 1260, -1, "", 1);// 547
			AddComplexComponent( (BaseAddon) this, 1329, 14, 6, 0, 1260, -1, "", 1);// 548
			AddComplexComponent( (BaseAddon) this, 1329, 14, 7, 0, 1260, -1, "", 1);// 549
			AddComplexComponent( (BaseAddon) this, 1329, 14, 8, 0, 1260, -1, "", 1);// 550
			AddComplexComponent( (BaseAddon) this, 1329, 14, 9, 0, 1260, -1, "", 1);// 551
			AddComplexComponent( (BaseAddon) this, 1329, 14, 10, 0, 1260, -1, "", 1);// 552
			AddComplexComponent( (BaseAddon) this, 1329, 14, 11, 0, 1260, -1, "", 1);// 553
			AddComplexComponent( (BaseAddon) this, 1329, 14, 12, 0, 1260, -1, "", 1);// 554
			AddComplexComponent( (BaseAddon) this, 1329, 14, 13, 0, 1260, -1, "", 1);// 555
			AddComplexComponent( (BaseAddon) this, 1329, 14, 14, 0, 1260, -1, "", 1);// 556
			AddComplexComponent( (BaseAddon) this, 1329, 15, -1, 0, 1260, -1, "", 1);// 557
			AddComplexComponent( (BaseAddon) this, 1329, 15, 0, 0, 1260, -1, "", 1);// 558
			AddComplexComponent( (BaseAddon) this, 1329, 15, 1, 0, 1260, -1, "", 1);// 559
			AddComplexComponent( (BaseAddon) this, 1329, 15, 2, 0, 1260, -1, "", 1);// 560
			AddComplexComponent( (BaseAddon) this, 1329, 15, 3, 0, 1260, -1, "", 1);// 561
			AddComplexComponent( (BaseAddon) this, 1329, 15, 4, 0, 1260, -1, "", 1);// 562
			AddComplexComponent( (BaseAddon) this, 1329, 15, 5, 0, 1260, -1, "", 1);// 563
			AddComplexComponent( (BaseAddon) this, 1329, 15, 6, 0, 1260, -1, "", 1);// 564
			AddComplexComponent( (BaseAddon) this, 1329, 15, 7, 0, 1260, -1, "", 1);// 565
			AddComplexComponent( (BaseAddon) this, 1329, 15, 8, 0, 1260, -1, "", 1);// 566
			AddComplexComponent( (BaseAddon) this, 1329, 15, 9, 0, 1260, -1, "", 1);// 567
			AddComplexComponent( (BaseAddon) this, 1329, 15, 10, 0, 1260, -1, "", 1);// 568
			AddComplexComponent( (BaseAddon) this, 1329, 15, 11, 0, 1260, -1, "", 1);// 569
			AddComplexComponent( (BaseAddon) this, 1329, 15, 12, 0, 1260, -1, "", 1);// 570
			AddComplexComponent( (BaseAddon) this, 1329, 15, 13, 0, 1260, -1, "", 1);// 571
			AddComplexComponent( (BaseAddon) this, 1329, 15, 14, 0, 1260, -1, "", 1);// 572
			AddComplexComponent( (BaseAddon) this, 1329, 16, -1, 0, 1260, -1, "", 1);// 573
			AddComplexComponent( (BaseAddon) this, 1329, 16, 0, 0, 1260, -1, "", 1);// 574
			AddComplexComponent( (BaseAddon) this, 1329, 16, 1, 0, 1260, -1, "", 1);// 575
			AddComplexComponent( (BaseAddon) this, 1329, 16, 2, 0, 1260, -1, "", 1);// 576
			AddComplexComponent( (BaseAddon) this, 1329, 16, 3, 0, 1260, -1, "", 1);// 577
			AddComplexComponent( (BaseAddon) this, 1329, 16, 4, 0, 1260, -1, "", 1);// 578
			AddComplexComponent( (BaseAddon) this, 1329, 16, 5, 0, 1260, -1, "", 1);// 579
			AddComplexComponent( (BaseAddon) this, 1329, 16, 6, 0, 1260, -1, "", 1);// 580
			AddComplexComponent( (BaseAddon) this, 1329, 16, 7, 0, 1260, -1, "", 1);// 581
			AddComplexComponent( (BaseAddon) this, 1329, 16, 8, 0, 1260, -1, "", 1);// 582
			AddComplexComponent( (BaseAddon) this, 1329, 16, 9, 0, 1260, -1, "", 1);// 583
			AddComplexComponent( (BaseAddon) this, 1329, 16, 10, 0, 1260, -1, "", 1);// 584
			AddComplexComponent( (BaseAddon) this, 1329, 16, 11, 0, 1260, -1, "", 1);// 585
			AddComplexComponent( (BaseAddon) this, 1329, 16, 12, 0, 1260, -1, "", 1);// 586
			AddComplexComponent( (BaseAddon) this, 1329, 16, 13, 0, 1260, -1, "", 1);// 587
			AddComplexComponent( (BaseAddon) this, 1329, 16, 14, 0, 1260, -1, "", 1);// 588
			AddComplexComponent( (BaseAddon) this, 1329, 17, -1, 0, 1260, -1, "", 1);// 589
			AddComplexComponent( (BaseAddon) this, 1329, 17, 0, 0, 1260, -1, "", 1);// 590
			AddComplexComponent( (BaseAddon) this, 1329, 17, 1, 0, 1260, -1, "", 1);// 591
			AddComplexComponent( (BaseAddon) this, 1329, 17, 2, 0, 1260, -1, "", 1);// 592
			AddComplexComponent( (BaseAddon) this, 1329, 17, 3, 0, 1260, -1, "", 1);// 593
			AddComplexComponent( (BaseAddon) this, 1329, 17, 4, 0, 1260, -1, "", 1);// 594
			AddComplexComponent( (BaseAddon) this, 1329, 17, 5, 0, 1260, -1, "", 1);// 595
			AddComplexComponent( (BaseAddon) this, 1329, 17, 6, 0, 1260, -1, "", 1);// 596
			AddComplexComponent( (BaseAddon) this, 1329, 17, 7, 0, 1260, -1, "", 1);// 597
			AddComplexComponent( (BaseAddon) this, 1329, 17, 8, 0, 1260, -1, "", 1);// 598
			AddComplexComponent( (BaseAddon) this, 1329, 17, 9, 0, 1260, -1, "", 1);// 599
			AddComplexComponent( (BaseAddon) this, 1329, 17, 10, 0, 1260, -1, "", 1);// 600
			AddComplexComponent( (BaseAddon) this, 1329, 17, 11, 0, 1260, -1, "", 1);// 601
			AddComplexComponent( (BaseAddon) this, 1329, 17, 12, 0, 1260, -1, "", 1);// 602
			AddComplexComponent( (BaseAddon) this, 1329, 17, 13, 0, 1260, -1, "", 1);// 603
			AddComplexComponent( (BaseAddon) this, 1329, 17, 14, 0, 1260, -1, "", 1);// 604
			AddComplexComponent( (BaseAddon) this, 1329, 18, -1, 0, 1260, -1, "", 1);// 605
			AddComplexComponent( (BaseAddon) this, 1329, 18, 0, 0, 1260, -1, "", 1);// 606
			AddComplexComponent( (BaseAddon) this, 1329, 18, 1, 0, 1260, -1, "", 1);// 607
			AddComplexComponent( (BaseAddon) this, 1329, 18, 2, 0, 1260, -1, "", 1);// 608
			AddComplexComponent( (BaseAddon) this, 1329, 18, 3, 0, 1260, -1, "", 1);// 609
			AddComplexComponent( (BaseAddon) this, 1329, 18, 4, 0, 1260, -1, "", 1);// 610
			AddComplexComponent( (BaseAddon) this, 1329, 18, 5, 0, 1260, -1, "", 1);// 611
			AddComplexComponent( (BaseAddon) this, 1329, 18, 6, 0, 1260, -1, "", 1);// 612
			AddComplexComponent( (BaseAddon) this, 1329, 18, 7, 0, 1260, -1, "", 1);// 613
			AddComplexComponent( (BaseAddon) this, 1329, 18, 8, 0, 1260, -1, "", 1);// 614
			AddComplexComponent( (BaseAddon) this, 1329, 18, 9, 0, 1260, -1, "", 1);// 615
			AddComplexComponent( (BaseAddon) this, 1329, 18, 10, 0, 1260, -1, "", 1);// 616
			AddComplexComponent( (BaseAddon) this, 1329, 18, 11, 0, 1260, -1, "", 1);// 617
			AddComplexComponent( (BaseAddon) this, 1329, 18, 12, 0, 1260, -1, "", 1);// 618
			AddComplexComponent( (BaseAddon) this, 1329, 18, 13, 0, 1260, -1, "", 1);// 619
			AddComplexComponent( (BaseAddon) this, 1329, 18, 14, 0, 1260, -1, "", 1);// 620
			AddComplexComponent( (BaseAddon) this, 1329, 14, 15, 0, 1260, -1, "", 1);// 621
			AddComplexComponent( (BaseAddon) this, 1329, 14, 16, 0, 1260, -1, "", 1);// 622
			AddComplexComponent( (BaseAddon) this, 1329, 14, 17, 0, 1260, -1, "", 1);// 623
			AddComplexComponent( (BaseAddon) this, 1329, 14, 18, 0, 1260, -1, "", 1);// 624
			AddComplexComponent( (BaseAddon) this, 1329, 15, 15, 0, 1260, -1, "", 1);// 625
			AddComplexComponent( (BaseAddon) this, 1329, 15, 16, 0, 1260, -1, "", 1);// 626
			AddComplexComponent( (BaseAddon) this, 1329, 15, 17, 0, 1260, -1, "", 1);// 627
			AddComplexComponent( (BaseAddon) this, 1329, 15, 18, 0, 1260, -1, "", 1);// 628
			AddComplexComponent( (BaseAddon) this, 1329, 16, 15, 0, 1260, -1, "", 1);// 629
			AddComplexComponent( (BaseAddon) this, 1329, 16, 16, 0, 1260, -1, "", 1);// 630
			AddComplexComponent( (BaseAddon) this, 1329, 16, 17, 0, 1260, -1, "", 1);// 631
			AddComplexComponent( (BaseAddon) this, 1329, 16, 18, 0, 1260, -1, "", 1);// 632
			AddComplexComponent( (BaseAddon) this, 1329, 17, 15, 0, 1260, -1, "", 1);// 633
			AddComplexComponent( (BaseAddon) this, 1329, 17, 16, 0, 1260, -1, "", 1);// 634
			AddComplexComponent( (BaseAddon) this, 1329, 17, 17, 0, 1260, -1, "", 1);// 635
			AddComplexComponent( (BaseAddon) this, 1329, 17, 18, 0, 1260, -1, "", 1);// 636
			AddComplexComponent( (BaseAddon) this, 1329, 18, 15, 0, 1260, -1, "", 1);// 637
			AddComplexComponent( (BaseAddon) this, 1329, 18, 16, 0, 1260, -1, "", 1);// 638
			AddComplexComponent( (BaseAddon) this, 1329, 18, 17, 0, 1260, -1, "", 1);// 639
			AddComplexComponent( (BaseAddon) this, 1329, 18, 18, 0, 1260, -1, "", 1);// 640

		}

		public YellowBrickRoadParkSquareAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class YellowBrickRoadParkSquareAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new YellowBrickRoadParkSquareAddon();
			}
		}

		[Constructable]
		public YellowBrickRoadParkSquareAddonDeed()
		{
			Name = "YellowBrickRoadParkSquare";
		}

		public YellowBrickRoadParkSquareAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}