
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class zencornerlatticeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2000, -1, -1, 0}, {1993, 0, -1, 0}, {1993, 1, -1, 0}// 1	2	3	
			, {1993, 2, -1, 0}, {10082, -1, -2, 0}, {10082, 0, -2, 0}// 4	5	6	
			, {10082, 1, -2, 0}, {10082, 2, -2, 0}, {10079, -2, -1, 0}// 7	8	9	
			, {2861, 0, -1, 0}, {2861, 1, -1, 0}, {2861, 2, -1, 0}// 10	11	12	
			, {1848, -1, -1, 1}, {3308, 0, -1, 0}, {3308, 1, -1, 0}// 13	15	16	
			, {3308, 2, -1, 0}, {1997, -1, 0, 0}, {1997, -1, 1, 0}// 17	18	19	
			, {1997, -1, 2, 0}, {1997, -1, 3, 0}, {10079, -2, 0, 0}// 20	21	22	
			, {10079, -2, 1, 0}, {10079, -2, 2, 0}, {10078, -2, 3, 0}// 23	24	25	
			, {2860, -1, 0, 0}, {2860, -1, 1, 0}, {2860, -1, 2, 0}// 26	27	28	
			, {3312, -1, 1, 0}, {3312, -1, 2, 0}, {3312, -1, 0, 0}// 29	30	31	
			, {4551, -1, 3, 1}, {9037, -1, 3, 7}, {1993, 3, -1, 0}// 32	33	35	
			, {10081, 3, -2, 0}, {4551, 3, -1, 0}, {9037, 3, -1, 6}// 36	37	38	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new zencornerlatticeAddonDeed();
			}
		}

		[ Constructable ]
		public zencornerlatticeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 11534, -1, -1, 6, 0, -1, "ArcanistStatueEast", 1);// 14
			AddComplexComponent( (BaseAddon) this, 3219, -1, 3, 4, 0, -1, "Rose Bush", 1);// 34
			AddComplexComponent( (BaseAddon) this, 3219, 3, -1, 3, 0, -1, "Rose Bush", 1);// 39

		}

		public zencornerlatticeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class zencornerlatticeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new zencornerlatticeAddon();
			}
		}

		[Constructable]
		public zencornerlatticeAddonDeed()
		{
			Name = "zencornerlattice";
		}

		public zencornerlatticeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}