using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DoNDStageAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DoNDStageAddonDeed();
			}
		}

		[ Constructable ]
		public DoNDStageAddon()
		{
			AddonComponent ac;
			
			ac = new AddonComponent( 1809 );
				AddComponent( ac, 0, 7, 3 );
			ac = new AddonComponent( 1802 );
				AddComponent( ac, 1, 7, 3 );
			ac = new AddonComponent( 1807 );
				AddComponent( ac, 2, 7, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 7, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 7, -4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 7, -3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 7, -2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 7, -1, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 7, 0, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 7, 1, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 7, 2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 7, 3, 3 );
			ac = new AddonComponent( 1807 );
				AddComponent( ac, 7, 4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -3, -4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -3, -3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -3, -2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -2, -4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -2, -3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -2, -2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -1, -4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -1, -3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -1, -2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, -4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, -3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, -2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, -4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, -3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, -2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, -4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, -3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, -2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 3, -4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 3, -3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 3, -2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 4, -4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 4, -3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 4, -2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 5, -4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 5, -3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 5, -2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, -1, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -3, -4, 8 );
			ac = new AddonComponent( 1807 );
				AddComponent( ac, 5, -3, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -2, -4, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -2, -3, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -1, -4, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -1, -3, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, -4, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, -3, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, -4, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, -3, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, -4, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, -3, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 3, -4, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 3, -3, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 4, -4, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 4, -3, 8 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 5, -4, 8 );
			ac = new AddonComponent( 1809 );
				AddComponent( ac, -3, -3, 8 );
			ac = new AddonComponent( 1807 );
				AddComponent( ac, 4, -4, 13 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -1, -4, 13 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, -4, 13 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, -4, 13 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, -4, 13 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 3, -4, 13 );
			ac = new AddonComponent( 1809 );
				AddComponent( ac, -2, -4, 13 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, -1, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, 0, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 3, -1, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -1, -1, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, -1, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, 0, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -5, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -4, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -3, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -2, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -1, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 3, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 4, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 5, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 6, -5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -5, -4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -5, -3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -5, -2, 3 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, 4, -1, 6 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -5, -1, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -5, 0, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 6, 0, 0 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, 4, 0, 6 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 6, -1, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 6, -4, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 6, -3, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -4, -4, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -4, -3, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 3, 0, 5 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 4554 );
				AddComponent( ac, -1, 0, 11 );
			ac = new AddonComponent( 4554 );
				AddComponent( ac, 3, 0, 11 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, 6, 0, 6 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 272 );
				AddComponent( ac, 6, -2, 8 );
			ac = new AddonComponent( 272 );
				AddComponent( ac, 6, -1, 8 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, 5, 0, 6 );
			ac = new AddonComponent( 272 );
				AddComponent( ac, -5, -4, 8 );
			ac = new AddonComponent( 272 );
				AddComponent( ac, -5, -3, 8 );
			ac = new AddonComponent( 271 );
				AddComponent( ac, 6, -5, 6 );
			ac = new AddonComponent( 271 );
				AddComponent( ac, -4, -5, 8 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, -2, -1, 6 );
			ac = new AddonComponent( 272 );
				AddComponent( ac, 6, 0, 8 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, -4, -2, 6 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, -4, -1, 6 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, -4, -4, 6 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, -4, -3, 6 );
			ac = new AddonComponent( 272 );
				AddComponent( ac, 6, -4, 8 );
			ac = new AddonComponent( 272 );
				AddComponent( ac, 6, -3, 8 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, -2, 0, 6 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, -3, 0, 6 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, -3, -1, 6 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, 5, -1, 6 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, 6, -4, 6 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, 6, -2, 6 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, 6, -3, 6 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, 6, -1, 6 );
			ac = new AddonComponent( 3518 );
				AddComponent( ac, 4, -1, 6 );
			ac = new AddonComponent( 7385 );
				ac.Hue = 184;
				AddComponent( ac, -4, 0, 6 );
			ac = new AddonComponent( 272 );
				AddComponent( ac, -5, -2, 8 );
			ac = new AddonComponent( 272 );
				AddComponent( ac, -5, -1, 8 );
			ac = new AddonComponent( 272 );
				AddComponent( ac, -5, 0, 8 );
			ac = new AddonComponent( 273 );
				AddComponent( ac, -5, -5, 8 );
			ac = new AddonComponent( 2769 );
				AddComponent( ac, 1, -1, 9 );
			ac = new AddonComponent( 2770 );
				AddComponent( ac, 2, 0, 9 );
			ac = new AddonComponent( 2771 );
				AddComponent( ac, -1, -2, 9 );
			ac = new AddonComponent( 2772 );
				AddComponent( ac, 0, 0, 9 );
			ac = new AddonComponent( 2773 );
				AddComponent( ac, 3, -2, 9 );
			ac = new AddonComponent( 2775 );
				AddComponent( ac, 0, -2, 9 );
			ac = new AddonComponent( 2775 );
				AddComponent( ac, 1, -2, 9 );
			ac = new AddonComponent( 2775 );
				AddComponent( ac, 2, -2, 9 );
			ac = new AddonComponent( 2777 );
				AddComponent( ac, 1, 0, 9 );
			ac = new AddonComponent( 2776 );
				AddComponent( ac, 2, -1, 9 );
			ac = new AddonComponent( 2774 );
				AddComponent( ac, 0, -1, 9 );
			ac = new AddonComponent( 2772 );
				AddComponent( ac, -1, -1, 9 );
			ac = new AddonComponent( 2777 );
				AddComponent( ac, 0, -1, 9 );
			ac = new AddonComponent( 2777 );
				AddComponent( ac, 2, -1, 9 );
			ac = new AddonComponent( 2770 );
				AddComponent( ac, 3, -1, 9 );
			ac = new AddonComponent( 3339 );
				AddComponent( ac, -3, -1, 7 );
			ac = new AddonComponent( 3337 );
				AddComponent( ac, 5, -1, 8 );
			ac = new AddonComponent( 3338 );
				AddComponent( ac, -4, -3, 8 );
			ac = new AddonComponent( 3336 );
				AddComponent( ac, 5, -1, 8 );
			ac = new AddonComponent( 3336 );
				AddComponent( ac, -3, 0, 8 );
			ac = new AddonComponent( 7949 );
				AddComponent( ac, 6, -1, 8 );
			ac = new AddonComponent( 7949 );
				AddComponent( ac, 6, -4, 8 );
			ac = new AddonComponent( 7949 );
				AddComponent( ac, 6, -3, 8 );
			ac = new AddonComponent( 7949 );
				AddComponent( ac, 6, -2, 8 );
			ac = new AddonComponent( 7952 );
				AddComponent( ac, -4, -4, 8 );
			ac = new AddonComponent( 3518 );
				AddComponent( ac, -4, 1, 6 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, 1, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, 2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, 3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, 5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, 4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -1, 3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, 2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 0, 3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, 2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, 3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, 4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 3, 3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, 5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 1, 6, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, 4, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 2, 5, 3 );
			ac = new AddonComponent( 1803 );
				AddComponent( ac, 3, 5, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 4, 3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 5, 3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 6, 3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -2, 3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -3, 3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -4, 3, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -5, 1, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -5, 2, 3 );
			ac = new AddonComponent( 1801 );
				AddComponent( ac, -5, 3, 3 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, 6, 2, 6 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, 6, 1, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, 6, 1, 6 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, -3, 2, 0 );			
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1805 );
			        AddComponent( ac, -1, 5, 3 );
			ac = new AddonComponent( 1809 );
			        AddComponent( ac, -1, 6, 3 );
			ac = new AddonComponent( 1807 );			
			        AddComponent( ac, 3, 6, 3 );
			ac = new AddonComponent( 1809 );			
			        AddComponent( ac, -5, 4, 3 );
			ac = new AddonComponent( 1815 );
			        AddComponent( ac, 2, 6, 3 );
			ac = new AddonComponent( 1815 );
			        AddComponent( ac, 3, 4, 3 );
			ac = new AddonComponent( 1817 );
			        AddComponent( ac, 0, 6, 3 );
			ac = new AddonComponent( 1817 );
			        AddComponent( ac, -1, 4, 3 );
			ac = new AddonComponent( 1802 );
			        AddComponent( ac, 4, 4, 3 );
			ac = new AddonComponent( 1802 );
			        AddComponent( ac, 5, 4, 3 );
			ac = new AddonComponent( 1802 );
			        AddComponent( ac, 6, 4, 3 );
			ac = new AddonComponent( 1802 );
			        AddComponent( ac, -4, 4, 3 );
			ac = new AddonComponent( 1802 );
			        AddComponent( ac, -3, 4, 3 );
			ac = new AddonComponent( 1802 );
			        AddComponent( ac, -2, 4, 3 );
			ac = new AddonComponent( 7620 );
			        AddComponent( ac, 2, 2, 8 );
			ac = new AddonComponent( 1801 );
			        AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 7621 );
			        AddComponent( ac, 0, 2, 8 );
			ac = new AddonComponent( 7622 );
			        AddComponent( ac, 1, 2, 8 );
			ac = new AddonComponent( 7617 );
			        AddComponent( ac, 2, 3, 7 );
			ac = new AddonComponent( 7617 );
			        AddComponent( ac, 0, 3, 7 );
			ac = new AddonComponent( 271 );
			        AddComponent( ac, -4, 2, 8 );
			ac = new AddonComponent( 271 );
			        AddComponent( ac, -3, 2, 8 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, 5, 1, 6 );
			ac = new AddonComponent( 271 );
			        AddComponent( ac, 4, 2, 8 );
			ac = new AddonComponent( 271 );
			        AddComponent( ac, 5, 2, 8 );
			ac = new AddonComponent( 270 );
			        AddComponent( ac, 6, 2, 8 );
			ac = new AddonComponent( 271 );
			        AddComponent( ac, 3, 2, 8 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, -1, 2, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, 0, 1, 6 );
			ac = new AddonComponent( 271 );
			        AddComponent( ac, -2, 2, 8 );
			ac = new AddonComponent( 271 );
			        AddComponent( ac, -1, 2, 8 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, -2, 2, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, -1, 1, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, -3, 2, 6 );
			ac = new AddonComponent( 272 );
			        AddComponent( ac, 6, 1, 8 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, -2, 1, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, -3, 1, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, -4, 2, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, 4, 2, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, 4, 1, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, 5, 2, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, 3, 1, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, 3, 2, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, 2, 1, 6 );
			ac = new AddonComponent( 7385 );
			        ac.Hue = 184;
			        AddComponent( ac, -4, 1, 6 );
			ac = new AddonComponent( 272 );
			        AddComponent( ac, -5, 1, 8 );
			ac = new AddonComponent( 272 );
			        AddComponent( ac, -5, 2, 8 );
			ac = new AddonComponent( 7617 );
			        AddComponent( ac, 1, 3, 7 );
			ac = new AddonComponent( 7619 );
			        AddComponent( ac, 1, 3, 8 );
			ac = new AddonComponent( 7619 );
			        AddComponent( ac, 2, 3, 8 );
			ac = new AddonComponent( 7619 );
			        AddComponent( ac, 0, 3, 8 );
			ac = new AddonComponent( 2769 );
			        AddComponent( ac, 1, 4, 9 );
			ac = new AddonComponent( 2769 );
			        AddComponent( ac, 1, 5, 9 );
			ac = new AddonComponent( 2776 );
			        AddComponent( ac, 2, 5, 9 );
			ac = new AddonComponent( 2777 );
			        AddComponent( ac, 1, 6, 9 );
			ac = new AddonComponent( 2776 );
			        AddComponent( ac, 2, 4, 9 );
			ac = new AddonComponent( 2775 );
			        AddComponent( ac, 1, 3, 9 );
			ac = new AddonComponent( 2770 );
			        AddComponent( ac, 2, 6, 9 );
			ac = new AddonComponent( 2771 );
			        AddComponent( ac, 0, 3, 9 );
			ac = new AddonComponent( 2772 );
			        AddComponent( ac, 0, 6, 9 );
			ac = new AddonComponent( 2773 );
			        AddComponent( ac, 2, 3, 9 );
			ac = new AddonComponent( 2774 );
			        AddComponent( ac, 0, 4, 9 );
			ac = new AddonComponent( 2774 );
			        AddComponent( ac, 0, 5, 9 );
			ac = new AddonComponent( 3339 );
			        AddComponent( ac, 5, 1, 7 );
			ac = new AddonComponent( 3338 );
			        AddComponent( ac, -2, 1, 8 );
			ac = new AddonComponent( 3338 );
			        AddComponent( ac, 2, 1, 8 );
			ac = new AddonComponent( 3380 );
			        AddComponent( ac, 4, 1, 8 );
			ac = new AddonComponent( 7950 );
			        AddComponent( ac, -3, 2, 8 );
			ac = new AddonComponent( 7950 );
			        AddComponent( ac, -1, 2, 8 );
			ac = new AddonComponent( 7951 );
			        AddComponent( ac, -2, 2, 8 );
			ac = new AddonComponent( 7951 );
			        AddComponent( ac, 3, 2, 8 );
			ac = new AddonComponent( 7951 );
			        AddComponent( ac, 4, 2, 8 );
			ac = new AddonComponent( 3380 );
			        AddComponent( ac, -2, 1, 8 );
			ac = new AddonComponent( 4553 );
			        AddComponent( ac, 3, 3, 8 );
			ac = new AddonComponent( 4553 );
			        AddComponent( ac, -1, 3, 8 );
		}


		public DoNDStageAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DoNDStageAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DoNDStageAddon();
			}
		}

		[Constructable]
		public DoNDStageAddonDeed()
		{
			Name = "DoNDStage";
		}

		public DoNDStageAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}