
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarbleFireplaceSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1173, -1, -1, 0}, {1173, -1, 0, 0}, {1173, -1, 1, 0}// 1	2	3	
			, {1173, 0, -1, 0}, {1173, 0, 0, 0}, {1173, 0, 1, 0}// 4	5	6	
			, {1173, 1, -1, 0}, {1173, 1, 0, 0}, {1173, 1, 1, 0}// 7	8	9	
			, {1173, 2, -1, 0}, {1173, 2, 0, 0}, {1173, 2, 1, 0}// 10	11	12	
			, {1173, 3, -1, 0}, {1173, 3, 0, 0}, {1173, 3, 1, 0}// 13	14	15	
			, {1173, -2, -1, 0}, {1173, -2, 0, 0}, {1173, -2, 1, 0}// 16	17	18	
			, {261, -1, -1, 0}, {262, -2, -1, 0}, {275, 1, -1, 0}// 19	20	21	
			, {276, 0, -1, 0}, {279, 2, 0, 0}, {280, -1, 0, 0}// 22	23	24	
			, {280, 0, 0, 0}, {280, 1, 0, 0}, {281, -2, 0, 0}// 25	26	27	
			, {1981, 2, -1, 0}, {260, 2, -1, 0}, {11632, 2, 0, 0}// 31	32	37	
			, {11632, -1, 0, 0}, {7134, 0, -1, 2}, {7135, 3, -1, 0}// 38	41	43	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarbleFireplaceSouthAddonDeed();
			}
		}

		[ Constructable ]
		public MarbleFireplaceSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1981, -1, -1, 0, 1108, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1981, 0, -1, 0, 1108, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1981, 1, -1, 0, 1108, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1981, -1, 0, 0, 1108, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1981, 0, 0, 0, 1108, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1981, 1, 0, 0, 1108, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1981, 2, 0, 0, 1108, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 2562, -1, 0, 14, 0, 1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2562, 2, 0, 14, 0, 1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 6572, 0, -1, 7, 0, 1, "", 1);// 42

		}

		public MarbleFireplaceSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarbleFireplaceSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarbleFireplaceSouthAddon();
			}
		}

		[Constructable]
		public MarbleFireplaceSouthAddonDeed()
		{
			Name = "MarbleFireplaceSouth";
		}

		public MarbleFireplaceSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}