
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class oompatree4Addon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new oompatree4AddonDeed();
			}
		}

		[ Constructable ]
		public oompatree4Addon()
		{



			AddComplexComponent( (BaseAddon) this, 3500, 0, 0, 18, 2268, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3500, 0, 0, 12, 2266, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 9340, 1, 1, 32, 2345, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3500, 0, 0, 0, 2266, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3500, 0, 0, 30, 2268, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3500, 0, 0, 6, 2268, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3500, 0, 0, 24, 2266, -1, "", 1);// 7

		}

		public oompatree4Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class oompatree4AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new oompatree4Addon();
			}
		}

		[Constructable]
		public oompatree4AddonDeed()
		{
			Name = "oompatree4";
		}

		public oompatree4AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}