
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class orcfortwallpieceSAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2880, -2, 1, 0}, {2878, -1, 1, 0}, {2878, 0, 1, 0}// 1	2	3	
			, {2878, 1, 1, 0}, {2878, 2, 1, 0}, {1058, -2, 0, 0}// 4	5	6	
			, {1058, -1, 0, 0}, {1058, 0, 0, 0}, {1058, 1, 0, 0}// 7	8	9	
			, {1058, 2, 0, 0}, {1189, -2, 1, 6}, {1189, -1, 1, 6}// 10	11	12	
			, {1189, 0, 1, 6}, {1189, 1, 1, 6}, {1189, 2, 1, 6}// 13	14	15	
			, {2880, 3, 1, 0}, {1058, 3, 0, 0}, {1189, 3, 1, 6}// 16	17	18	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new orcfortwallpieceSAddonDeed();
			}
		}

		[ Constructable ]
		public orcfortwallpieceSAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public orcfortwallpieceSAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class orcfortwallpieceSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new orcfortwallpieceSAddon();
			}
		}

		[Constructable]
		public orcfortwallpieceSAddonDeed()
		{
			Name = "orcfortwallpieceS";
		}

		public orcfortwallpieceSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}