
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class PicnicBlanketEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2429, 1, 0, 2}, {2450, 1, 0, 1}, {2459, 1, 1, 7}// 17	18	30	
			, {2453, 1, 1, 0}, {2454, 1, 1, 3}// 31	32	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new PicnicBlanketEastAddonDeed();
			}
		}

		[ Constructable ]
		public PicnicBlanketEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2750, -1, -1, 1, 132, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2750, -1, 0, 1, 2461, -1, "blanket", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2750, 0, -1, 1, 2461, -1, "blanket", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2750, 0, 0, 1, 132, -1, "blanket", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2750, 1, -1, 1, 132, -1, "blanket", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2750, 1, 0, 1, 2461, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2755, -2, -2, 1, 2461, -1, "blanket", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2757, 2, -2, 1, 2461, -1, "blanket", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2806, -2, -1, 1, 132, -1, "blanket", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2806, -2, 0, 1, 132, -1, "blanket", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2807, -1, -2, 1, 132, -1, "blanket", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2807, 0, -2, 1, 132, -1, "blanket", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2807, 1, -2, 1, 132, -1, "blanket", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2808, 2, -1, 1, 132, -1, "blanket", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2808, 2, 0, 1, 132, -1, "blanket", 1);// 15
			AddComplexComponent( (BaseAddon) this, 5690, 0, 0, 11, 502, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 5690, -1, 0, 3, 502, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2750, -1, 1, 1, 132, -1, "blanket", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2750, 0, 1, 1, 2461, -1, "blanket", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2750, 1, 1, 1, 132, -1, "blanket", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2754, 2, 2, 1, 2461, -1, "blanket", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2756, -2, 2, 1, 2461, -1, "blanket", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2806, -2, 1, 1, 132, -1, "blanket", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2808, 2, 1, 1, 132, -1, "blanket", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2809, -1, 2, 1, 132, -1, "blanket", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2809, 0, 2, 1, 132, -1, "blanket", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2809, 1, 2, 1, 132, -1, "blanket", 1);// 29

		}

		public PicnicBlanketEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class PicnicBlanketEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new PicnicBlanketEastAddon();
			}
		}

		[Constructable]
		public PicnicBlanketEastAddonDeed()
		{
			Name = "PicnicBlanketEast";
		}

		public PicnicBlanketEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}