
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class sandstonecouchnorthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1900, -2, 0, 0}, {1900, -2, 1, 0}, {1900, -1, 1, 0}// 1	2	3	
			, {7627, -1, 0, 0}, {1900, 0, 1, 0}, {1900, 1, 1, 0}// 4	5	6	
			, {1900, 2, 0, 0}, {1900, 2, 1, 0}, {7628, 0, 0, 0}// 7	8	9	
			, {7626, 1, 0, 0}// 10	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new sandstonecouchnorthAddonDeed();
			}
		}

		[ Constructable ]
		public sandstonecouchnorthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public sandstonecouchnorthAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class sandstonecouchnorthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new sandstonecouchnorthAddon();
			}
		}

		[Constructable]
		public sandstonecouchnorthAddonDeed()
		{
			Name = "sandstonecouchnorth";
		}

		public sandstonecouchnorthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}