
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SquareDisplayCase4Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2831, -1, -1, 0}, {2831, -1, 0, 0}, {2831, -1, 1, 0}// 1	2	3	
			, {2832, -2, -2, 0}, {2834, -2, 2, 0}, {2837, -1, 2, 0}// 4	5	6	
			, {2838, -2, -1, 0}, {2838, -2, 0, 0}, {2838, -2, 1, 0}// 7	8	9	
			, {2839, -1, -2, 0}, {2723, -2, -2, 3}, {2725, -2, 2, 3}// 10	11	12	
			, {2722, -1, -2, 3}, {2721, -2, -1, 3}, {2721, -2, 0, 3}// 13	14	15	
			, {2721, -2, 1, 3}, {2720, -1, 2, 3}, {2831, 0, -1, 0}// 16	17	18	
			, {2831, 1, -1, 0}, {2831, 0, 0, 0}, {2831, 1, 0, 0}// 19	20	21	
			, {2831, 0, 1, 0}, {2831, 1, 1, 0}, {2833, 2, 2, 0}// 22	23	24	
			, {2835, 2, -2, 0}, {2836, 2, -1, 0}, {2836, 2, 0, 0}// 25	26	27	
			, {2836, 2, 1, 0}, {2837, 0, 2, 0}, {2837, 1, 2, 0}// 28	29	30	
			, {2839, 0, -2, 0}, {2839, 1, -2, 0}, {2840, 2, 2, 3}// 31	32	33	
			, {2724, 2, -2, 3}, {2722, 0, -2, 3}, {2722, 1, -2, 3}// 34	35	36	
			, {2720, 0, 2, 3}, {2720, 1, 2, 3}, {2719, 2, -1, 3}// 37	38	39	
			, {2719, 2, 0, 3}, {2719, 2, 1, 3}// 40	41	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SquareDisplayCase4AddonDeed();
			}
		}

		[ Constructable ]
		public SquareDisplayCase4Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public SquareDisplayCase4Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SquareDisplayCase4AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SquareDisplayCase4Addon();
			}
		}

		[Constructable]
		public SquareDisplayCase4AddonDeed()
		{
			Name = "SquareDisplayCase4";
		}

		public SquareDisplayCase4AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}