/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class UnderTheSeaWallSAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new UnderTheSeaWallSAddonDeed();
			}
		}

		[ Constructable ]
		public UnderTheSeaWallSAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 605 );
			ac.Hue = 99;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 607 );
			ac.Hue = 99;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 609 );
			ac.Hue = 99;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 605 );
			ac.Hue = 99;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 607 );
			ac.Hue = 99;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 607 );
			ac.Hue = 99;
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 609 );
			ac.Hue = 99;
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 613 );
			ac.Hue = 99;
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 617 );
			ac.Hue = 99;
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1339 );
			ac.Hue = 99;
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 1339 );
			ac.Hue = 99;
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 1339 );
			ac.Hue = 99;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1339 );
			ac.Hue = 99;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1339 );
			ac.Hue = 99;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1339 );
			ac.Hue = 99;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1339 );
			ac.Hue = 99;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1339 );
			ac.Hue = 99;
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1339 );
			ac.Hue = 99;
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 8109 );
			AddComponent( ac, -1, 1, 0 );

		}

		public UnderTheSeaWallSAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class UnderTheSeaWallSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new UnderTheSeaWallSAddon();
			}
		}

		[Constructable]
		public UnderTheSeaWallSAddonDeed()
		{
			Name = "UnderTheSeaWallS";
		}

		public UnderTheSeaWallSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}