
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class VineSwingEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2916, 0, -1, 0}, {2916, 0, 0, 0}// 2	3	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new VineSwingEastAddonDeed();
			}
		}

		[ Constructable ]
		public VineSwingEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2967, 0, -1, 2, 0, -1, "Swing Hanger", 1);// 1
			AddComplexComponent( (BaseAddon) this, 7833, 0, 1, 5, 1819, -1, "Swing Vine", 1);// 4
			AddComplexComponent( (BaseAddon) this, 7833, 0, 1, 9, 1819, -1, "Swing Vine", 1);// 5
			AddComplexComponent( (BaseAddon) this, 7833, 0, 1, 13, 1819, -1, "Swing Vine", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2967, 0, 1, 3, 0, -1, "Swing Hanger", 1);// 7
			AddComplexComponent( (BaseAddon) this, 7833, 0, -1, 5, 1819, -1, "Swing Vine", 1);// 8
			AddComplexComponent( (BaseAddon) this, 7833, 0, -1, 8, 1819, -1, "Swing Vine", 1);// 9
			AddComplexComponent( (BaseAddon) this, 7833, 0, -1, 12, 1819, -1, "Swing Vine", 1);// 10
			AddComplexComponent( (BaseAddon) this, 7830, 1, 1, 8, 1819, -1, "Swing Vine", 1);// 11
			AddComplexComponent( (BaseAddon) this, 7830, 1, 1, 13, 1819, -1, "Swing Vine", 1);// 12
			AddComplexComponent( (BaseAddon) this, 7830, 1, 1, 18, 1819, -1, "Swing Vine", 1);// 13
			AddComplexComponent( (BaseAddon) this, 7830, 1, -1, 8, 1819, -1, "Swing Vine", 1);// 14
			AddComplexComponent( (BaseAddon) this, 7830, 1, -1, 12, 1819, -1, "Swing Vine", 1);// 15
			AddComplexComponent( (BaseAddon) this, 7830, 1, -1, 16, 1819, -1, "Swing Vine", 1);// 16

		}

		public VineSwingEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class VineSwingEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new VineSwingEastAddon();
			}
		}

		[Constructable]
		public VineSwingEastAddonDeed()
		{
			Name = "VineSwingEast";
		}

		public VineSwingEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}