
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class zencornersandstone2Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {361, -2, 3, 3}, {1901, 0, -1, 0}, {3310, -1, 3, 12}// 1	2	3	
			, {3309, -1, 0, 3}, {1901, 1, -1, 0}, {1907, 3, -2, 2}// 4	6	7	
			, {1902, -1, 2, 0}, {352, -1, -2, 2}, {1900, -1, -1, 2}// 8	10	16	
			, {362, 3, -2, 3}, {1902, -1, 0, 0}, {351, -2, 2, 2}// 17	18	19	
			, {4554, 3, -1, 7}, {1901, 2, -1, 0}, {3309, 0, -1, 5}// 22	24	26	
			, {1902, -1, 1, 0}, {353, -2, -2, 2}, {351, -2, -1, 2}// 27	28	29	
			, {352, 2, -2, 2}, {1908, -2, 3, 2}, {4554, -1, 3, 7}// 30	31	32	
			, {3310, 2, -1, 3}, {1900, 3, -1, 2}, {1900, -1, 3, 2}// 33	34	35	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new zencornersandstone2AddonDeed();
			}
		}

		[ Constructable ]
		public zencornersandstone2Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 354, -2, 1, 2, 0, 1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2922, 1, -1, 2, 0, -1, "Marble Bench", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2914, -1, 2, 1, 0, -1, "Marble Bench", 1);// 11
			AddComplexComponent( (BaseAddon) this, 355, 1, -2, 2, 0, 1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 11534, -1, -1, 9, 0, -1, "ArcanistStatueEast", 1);// 13
			AddComplexComponent( (BaseAddon) this, 354, -2, 0, 2, 0, 1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2920, 2, -1, 2, 0, -1, "Marble Bench", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2915, -1, 0, 1, 0, -1, "Marble Bench", 1);// 20
			AddComplexComponent( (BaseAddon) this, 355, 0, -2, 2, 0, 1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2916, -1, 1, 1, 0, -1, "Marble Bench", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2921, 0, -1, 2, 0, -1, "Marble Bench", 1);// 25

		}

		public zencornersandstone2Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class zencornersandstone2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new zencornersandstone2Addon();
			}
		}

		[Constructable]
		public zencornersandstone2AddonDeed()
		{
			Name = "zencornersandstone2";
		}

		public zencornersandstone2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}